# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.coordination.v1alpha2._official_async import (
    _OfficialCoordinationV1Alpha2AsyncOperations,
)


class AsyncCoordinationV1Alpha2API(_OfficialCoordinationV1Alpha2AsyncOperations):
    pass
