# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.coordination.v1alpha2._official_sync import (
    _OfficialCoordinationV1Alpha2SyncOperations,
)


class CoordinationV1Alpha2API(_OfficialCoordinationV1Alpha2SyncOperations):
    pass
