# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.admissionregistration.v1beta1._official_async import (
    _OfficialAdmissionRegistrationV1Beta1AsyncOperations,
)


class AsyncAdmissionRegistrationV1Beta1API(_OfficialAdmissionRegistrationV1Beta1AsyncOperations):
    pass
