# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.admissionregistration.v1beta1._official_sync import (
    _OfficialAdmissionRegistrationV1Beta1SyncOperations,
)


class AdmissionRegistrationV1Beta1API(_OfficialAdmissionRegistrationV1Beta1SyncOperations):
    pass
