# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s._official_api import OfficialOperation, OperationParameter

OPERATIONS: tuple[OfficialOperation, ...] = (
    OfficialOperation(
        key="GET /apis/authentication.k8s.io/v1beta1/",
        operation_id="getAuthenticationV1beta1APIResources",
        method_name="get_api_resources",
        api="AuthenticationV1Beta1API",
        client_property="authentication_v1beta1",
        method="GET",
        path="/apis/authentication.k8s.io/v1beta1/",
        action=None,
        group=None,
        version=None,
        kind=None,
        namespaced=False,
        parameters=(),
        request_schema=None,
        response_schema="io.k8s.apimachinery.pkg.apis.meta.v1.APIResourceList",
        request_media_types=(),
        response_media_types=(
            "application/cbor",
            "application/json",
            "application/vnd.kubernetes.protobuf",
            "application/yaml",
        ),
        streaming=None,
        kubernetes_versions=("v1.31.0", "v1.32.0"),
    ),
    OfficialOperation(
        key="POST /apis/authentication.k8s.io/v1beta1/selfsubjectreviews",
        operation_id="createAuthenticationV1beta1SelfSubjectReview",
        method_name="create_self_subject_review",
        api="AuthenticationV1Beta1API",
        client_property="authentication_v1beta1",
        method="POST",
        path="/apis/authentication.k8s.io/v1beta1/selfsubjectreviews",
        action="post",
        group="authentication.k8s.io",
        version="v1beta1",
        kind="SelfSubjectReview",
        namespaced=False,
        parameters=(
            OperationParameter(
                wire_name="dryRun",
                python_name="dry_run",
                location="query",
                required=False,
                schema_type="str",
            ),
            OperationParameter(
                wire_name="fieldManager",
                python_name="field_manager",
                location="query",
                required=False,
                schema_type="str",
            ),
            OperationParameter(
                wire_name="fieldValidation",
                python_name="field_validation",
                location="query",
                required=False,
                schema_type="str",
            ),
            OperationParameter(
                wire_name="pretty",
                python_name="pretty",
                location="query",
                required=False,
                schema_type="str",
            ),
        ),
        request_schema="io.k8s.api.authentication.v1beta1.SelfSubjectReview",
        response_schema="io.k8s.api.authentication.v1beta1.SelfSubjectReview",
        request_media_types=("*/*",),
        response_media_types=(
            "application/cbor",
            "application/json",
            "application/vnd.kubernetes.protobuf",
            "application/yaml",
        ),
        streaming=None,
        kubernetes_versions=("v1.31.0", "v1.32.0"),
    ),
)

OPERATIONS_BY_METHOD = {item.method_name: item for item in OPERATIONS}
