# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.authentication.v1beta1._official_sync import (
    _OfficialAuthenticationV1Beta1SyncOperations,
)


class AuthenticationV1Beta1API(_OfficialAuthenticationV1Beta1SyncOperations):
    pass
