# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.storage.v1alpha1._sync import StorageV1Alpha1API as StorageV1Alpha1API
from httpx2_k8s.storage.v1alpha1._async import AsyncStorageV1Alpha1API as AsyncStorageV1Alpha1API
from httpx2_k8s.storage.v1alpha1._models import (
    StorageV1Alpha1VolumeAttributesClass as StorageV1Alpha1VolumeAttributesClass,
    StorageV1Alpha1VolumeAttributesClassList as StorageV1Alpha1VolumeAttributesClassList,
)

__all__ = [
    "AsyncStorageV1Alpha1API",
    "StorageV1Alpha1API",
    "StorageV1Alpha1VolumeAttributesClass",
    "StorageV1Alpha1VolumeAttributesClassList",
]
