# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1Condition,
    MetaV1LabelSelector,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
)


class AdmissionRegistrationV1AuditAnnotation(KubeModel):
    key: str = Field(default="", alias="key")
    value_expression: str = Field(default="", alias="valueExpression")


class AdmissionRegistrationV1ExpressionWarning(KubeModel):
    field_ref: str = Field(default="", alias="fieldRef")
    warning: str = Field(default="", alias="warning")


class AdmissionRegistrationV1MatchCondition(KubeModel):
    expression: str = Field(default="", alias="expression")
    name: str = Field(default="", alias="name")


class AdmissionRegistrationV1MatchResources(KubeModel):
    exclude_resource_rules: list[AdmissionRegistrationV1NamedRuleWithOperations] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="excludeResourceRules",
    )
    match_policy: str | None = Field(default=None, alias="matchPolicy")
    namespace_selector: MetaV1LabelSelector | None = Field(default=None, alias="namespaceSelector")
    object_selector: MetaV1LabelSelector | None = Field(default=None, alias="objectSelector")
    resource_rules: list[AdmissionRegistrationV1NamedRuleWithOperations] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceRules"
    )


class AdmissionRegistrationV1MutatingWebhook(KubeModel):
    admission_review_versions: list[str] = Field(
        json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="admissionReviewVersions"
    )
    client_config: AdmissionRegistrationV1WebhookClientConfig = Field(
        default_factory=lambda: AdmissionRegistrationV1WebhookClientConfig.model_construct(),
        alias="clientConfig",
    )
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_policy: str | None = Field(default=None, alias="matchPolicy")
    name: str = Field(default="", alias="name")
    namespace_selector: MetaV1LabelSelector | None = Field(default=None, alias="namespaceSelector")
    object_selector: MetaV1LabelSelector | None = Field(default=None, alias="objectSelector")
    reinvocation_policy: str | None = Field(default=None, alias="reinvocationPolicy")
    rules: list[AdmissionRegistrationV1RuleWithOperations] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="rules"
    )
    side_effects: str = Field(alias="sideEffects")
    timeout_seconds: int | None = Field(default=None, alias="timeoutSeconds")


class AdmissionRegistrationV1MutatingWebhookConfiguration(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["MutatingWebhookConfiguration"] = Field(
        default="MutatingWebhookConfiguration", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    webhooks: list[AdmissionRegistrationV1MutatingWebhook] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="webhooks",
    )


class AdmissionRegistrationV1MutatingWebhookConfigurationList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1MutatingWebhookConfiguration] = Field(alias="items")
    kind: Literal["MutatingWebhookConfigurationList"] = Field(
        default="MutatingWebhookConfigurationList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1NamedRuleWithOperations(KubeModel):
    api_groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiGroups"
    )
    api_versions: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiVersions"
    )
    operations: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="operations"
    )
    resource_names: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceNames"
    )
    resources: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resources"
    )
    scope: str | None = Field(default=None, alias="scope")


class AdmissionRegistrationV1ParamKind(KubeModel):
    api_version: str | None = Field(default=None, alias="apiVersion")
    kind: str | None = Field(default=None, alias="kind")


class AdmissionRegistrationV1ParamRef(KubeModel):
    name: str | None = Field(default=None, alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    parameter_not_found_action: str | None = Field(default=None, alias="parameterNotFoundAction")
    selector: MetaV1LabelSelector | None = Field(default=None, alias="selector")


class AdmissionRegistrationV1RuleWithOperations(KubeModel):
    api_groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiGroups"
    )
    api_versions: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiVersions"
    )
    operations: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="operations"
    )
    resources: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resources"
    )
    scope: str | None = Field(default=None, alias="scope")


class AdmissionRegistrationV1ServiceReference(KubeModel):
    name: str = Field(default="", alias="name")
    namespace: str = Field(default="", alias="namespace")
    path: str | None = Field(default=None, alias="path")
    port: int | None = Field(default=None, alias="port")


class AdmissionRegistrationV1TypeChecking(KubeModel):
    expression_warnings: list[AdmissionRegistrationV1ExpressionWarning] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="expressionWarnings",
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicy(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ValidatingAdmissionPolicy"] = Field(
        default="ValidatingAdmissionPolicy", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1ValidatingAdmissionPolicySpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1ValidatingAdmissionPolicySpec.model_construct()
        ),
        alias="spec",
    )
    status: AdmissionRegistrationV1ValidatingAdmissionPolicyStatus = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1ValidatingAdmissionPolicyStatus.model_construct()
        ),
        alias="status",
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicyBinding(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ValidatingAdmissionPolicyBinding"] = Field(
        default="ValidatingAdmissionPolicyBinding", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1ValidatingAdmissionPolicyBindingSpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1ValidatingAdmissionPolicyBindingSpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicyBindingList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1ValidatingAdmissionPolicyBinding] = Field(alias="items")
    kind: Literal["ValidatingAdmissionPolicyBindingList"] = Field(
        default="ValidatingAdmissionPolicyBindingList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicyBindingSpec(KubeModel):
    match_resources: AdmissionRegistrationV1MatchResources | None = Field(
        default=None, alias="matchResources"
    )
    param_ref: AdmissionRegistrationV1ParamRef | None = Field(default=None, alias="paramRef")
    policy_name: str | None = Field(default=None, alias="policyName")
    validation_actions: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "set"}, alias="validationActions"
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicyList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1ValidatingAdmissionPolicy] = Field(alias="items")
    kind: Literal["ValidatingAdmissionPolicyList"] = Field(
        default="ValidatingAdmissionPolicyList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicySpec(KubeModel):
    audit_annotations: list[AdmissionRegistrationV1AuditAnnotation] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="auditAnnotations",
    )
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_constraints: AdmissionRegistrationV1MatchResources | None = Field(
        default=None, alias="matchConstraints"
    )
    param_kind: AdmissionRegistrationV1ParamKind | None = Field(default=None, alias="paramKind")
    validations: list[AdmissionRegistrationV1Validation] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="validations"
    )
    variables: list[AdmissionRegistrationV1Variable] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="variables",
    )


class AdmissionRegistrationV1ValidatingAdmissionPolicyStatus(KubeModel):
    conditions: list[MetaV1Condition] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-map-keys": ["type"], "x-kubernetes-list-type": "map"},
        alias="conditions",
    )
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    type_checking: AdmissionRegistrationV1TypeChecking | None = Field(
        default=None, alias="typeChecking"
    )


class AdmissionRegistrationV1ValidatingWebhook(KubeModel):
    admission_review_versions: list[str] = Field(
        json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="admissionReviewVersions"
    )
    client_config: AdmissionRegistrationV1WebhookClientConfig = Field(
        default_factory=lambda: AdmissionRegistrationV1WebhookClientConfig.model_construct(),
        alias="clientConfig",
    )
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_policy: str | None = Field(default=None, alias="matchPolicy")
    name: str = Field(default="", alias="name")
    namespace_selector: MetaV1LabelSelector | None = Field(default=None, alias="namespaceSelector")
    object_selector: MetaV1LabelSelector | None = Field(default=None, alias="objectSelector")
    rules: list[AdmissionRegistrationV1RuleWithOperations] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="rules"
    )
    side_effects: str = Field(alias="sideEffects")
    timeout_seconds: int | None = Field(default=None, alias="timeoutSeconds")


class AdmissionRegistrationV1ValidatingWebhookConfiguration(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ValidatingWebhookConfiguration"] = Field(
        default="ValidatingWebhookConfiguration", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    webhooks: list[AdmissionRegistrationV1ValidatingWebhook] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="webhooks",
    )


class AdmissionRegistrationV1ValidatingWebhookConfigurationList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1ValidatingWebhookConfiguration] = Field(alias="items")
    kind: Literal["ValidatingWebhookConfigurationList"] = Field(
        default="ValidatingWebhookConfigurationList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1Validation(KubeModel):
    expression: str = Field(default="", alias="expression")
    message: str | None = Field(default=None, alias="message")
    message_expression: str | None = Field(default=None, alias="messageExpression")
    reason: str | None = Field(default=None, alias="reason")


class AdmissionRegistrationV1Variable(KubeModel):
    expression: str = Field(default="", alias="expression")
    name: str = Field(default="", alias="name")


class AdmissionRegistrationV1WebhookClientConfig(KubeModel):
    ca_bundle: Base64Data | None = Field(default=None, alias="caBundle")
    service: AdmissionRegistrationV1ServiceReference | None = Field(default=None, alias="service")
    url: str | None = Field(default=None, alias="url")


class AdmissionRegistrationV1ApplyConfiguration(KubeModel):
    expression: str | None = Field(default=None, alias="expression")


class AdmissionRegistrationV1JSONPatch(KubeModel):
    expression: str | None = Field(default=None, alias="expression")


class AdmissionRegistrationV1MutatingAdmissionPolicy(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["MutatingAdmissionPolicy"] = Field(
        default="MutatingAdmissionPolicy", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1MutatingAdmissionPolicySpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1MutatingAdmissionPolicySpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1MutatingAdmissionPolicyBinding(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["MutatingAdmissionPolicyBinding"] = Field(
        default="MutatingAdmissionPolicyBinding", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1MutatingAdmissionPolicyBindingSpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1MutatingAdmissionPolicyBindingSpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1MutatingAdmissionPolicyBindingList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1MutatingAdmissionPolicyBinding] = Field(alias="items")
    kind: Literal["MutatingAdmissionPolicyBindingList"] = Field(
        default="MutatingAdmissionPolicyBindingList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1MutatingAdmissionPolicyBindingSpec(KubeModel):
    match_resources: AdmissionRegistrationV1MatchResources | None = Field(
        default=None, alias="matchResources"
    )
    param_ref: AdmissionRegistrationV1ParamRef | None = Field(default=None, alias="paramRef")
    policy_name: str | None = Field(default=None, alias="policyName")


class AdmissionRegistrationV1MutatingAdmissionPolicyList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1"] = Field(
        default="admissionregistration.k8s.io/v1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1MutatingAdmissionPolicy] = Field(alias="items")
    kind: Literal["MutatingAdmissionPolicyList"] = Field(
        default="MutatingAdmissionPolicyList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1MutatingAdmissionPolicySpec(KubeModel):
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_constraints: AdmissionRegistrationV1MatchResources | None = Field(
        default=None, alias="matchConstraints"
    )
    mutations: list[AdmissionRegistrationV1Mutation] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="mutations"
    )
    param_kind: AdmissionRegistrationV1ParamKind | None = Field(default=None, alias="paramKind")
    reinvocation_policy: str | None = Field(default=None, alias="reinvocationPolicy")
    variables: list[AdmissionRegistrationV1Variable] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="variables"
    )


class AdmissionRegistrationV1Mutation(KubeModel):
    apply_configuration: AdmissionRegistrationV1ApplyConfiguration | None = Field(
        default=None, alias="applyConfiguration"
    )
    json_patch: AdmissionRegistrationV1JSONPatch | None = Field(default=None, alias="jsonPatch")
    patch_type: str = Field(default="", alias="patchType")


__all__ = [
    "AdmissionRegistrationV1AuditAnnotation",
    "AdmissionRegistrationV1ExpressionWarning",
    "AdmissionRegistrationV1MatchCondition",
    "AdmissionRegistrationV1MatchResources",
    "AdmissionRegistrationV1MutatingWebhook",
    "AdmissionRegistrationV1MutatingWebhookConfiguration",
    "AdmissionRegistrationV1MutatingWebhookConfigurationList",
    "AdmissionRegistrationV1NamedRuleWithOperations",
    "AdmissionRegistrationV1ParamKind",
    "AdmissionRegistrationV1ParamRef",
    "AdmissionRegistrationV1RuleWithOperations",
    "AdmissionRegistrationV1ServiceReference",
    "AdmissionRegistrationV1TypeChecking",
    "AdmissionRegistrationV1ValidatingAdmissionPolicy",
    "AdmissionRegistrationV1ValidatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1ValidatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1ValidatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1ValidatingAdmissionPolicyList",
    "AdmissionRegistrationV1ValidatingAdmissionPolicySpec",
    "AdmissionRegistrationV1ValidatingAdmissionPolicyStatus",
    "AdmissionRegistrationV1ValidatingWebhook",
    "AdmissionRegistrationV1ValidatingWebhookConfiguration",
    "AdmissionRegistrationV1ValidatingWebhookConfigurationList",
    "AdmissionRegistrationV1Validation",
    "AdmissionRegistrationV1Variable",
    "AdmissionRegistrationV1WebhookClientConfig",
    "AdmissionRegistrationV1ApplyConfiguration",
    "AdmissionRegistrationV1JSONPatch",
    "AdmissionRegistrationV1MutatingAdmissionPolicy",
    "AdmissionRegistrationV1MutatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1MutatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1MutatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1MutatingAdmissionPolicyList",
    "AdmissionRegistrationV1MutatingAdmissionPolicySpec",
    "AdmissionRegistrationV1Mutation",
]
