# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Iterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_watch_response, query_parameters
from httpx2_k8s._protocols import SyncKubeClientProtocol
from httpx2_k8s.admissionregistration.v1._models import (
    AdmissionRegistrationV1MutatingAdmissionPolicy,
    AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
    AdmissionRegistrationV1MutatingAdmissionPolicyBindingList,
    AdmissionRegistrationV1MutatingAdmissionPolicyList,
    AdmissionRegistrationV1MutatingWebhookConfiguration,
    AdmissionRegistrationV1MutatingWebhookConfigurationList,
    AdmissionRegistrationV1ValidatingAdmissionPolicy,
    AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
    AdmissionRegistrationV1ValidatingAdmissionPolicyBindingList,
    AdmissionRegistrationV1ValidatingAdmissionPolicyList,
    AdmissionRegistrationV1ValidatingWebhookConfiguration,
    AdmissionRegistrationV1ValidatingWebhookConfigurationList,
)
from httpx2_k8s.apimachinery import (
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
)


class _OfficialAdmissionRegistrationV1SyncOperations:
    _client: SyncKubeClientProtocol

    def official_delete_collection_mutating_webhook_configuration(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_mutating_webhook_configuration(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_collection_validating_admission_policy(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_validating_admission_policy(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_collection_validating_admission_policy_binding(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_validating_admission_policy_binding(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_collection_validating_webhook_configuration(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_validating_webhook_configuration(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/admissionregistration.k8s.io/v1/"
        params = {}
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    def official_list_mutating_webhook_configuration(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1MutatingWebhookConfigurationList:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingWebhookConfigurationList,
            params=params,
        )

    def official_read_mutating_webhook_configuration(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1MutatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingWebhookConfiguration,
            params=params,
        )

    def official_list_validating_admission_policy(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyList:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyList,
            params=params,
        )

    def official_read_validating_admission_policy(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
        )

    def official_read_validating_admission_policy_status(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
        )

    def official_list_validating_admission_policy_binding(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyBindingList:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyBindingList,
            params=params,
        )

    def official_read_validating_admission_policy_binding(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
            params=params,
        )

    def official_list_validating_webhook_configuration(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1ValidatingWebhookConfigurationList:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingWebhookConfigurationList,
            params=params,
        )

    def official_read_validating_webhook_configuration(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1ValidatingWebhookConfiguration,
            params=params,
        )

    def watch_mutating_webhook_configuration_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/mutatingwebhookconfigurations"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_mutating_webhook_configuration(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/mutatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_admission_policy_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/validatingadmissionpolicies"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_admission_policy(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/validatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_admission_policy_binding_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/validatingadmissionpolicybindings"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_admission_policy_binding(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/validatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_webhook_configuration_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/validatingwebhookconfigurations"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_validating_webhook_configuration(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/validatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def official_patch_mutating_webhook_configuration(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1MutatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1MutatingWebhookConfiguration,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_validating_admission_policy(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_validating_admission_policy_status(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_validating_admission_policy_binding(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_validating_webhook_configuration(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1ValidatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1ValidatingWebhookConfiguration,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_create_mutating_webhook_configuration(
        self,
        body: AdmissionRegistrationV1MutatingWebhookConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingWebhookConfiguration:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1MutatingWebhookConfiguration,
            params=params,
            body=body,
        )

    def official_create_validating_admission_policy(
        self,
        body: AdmissionRegistrationV1ValidatingAdmissionPolicy,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
            body=body,
        )

    def official_create_validating_admission_policy_binding(
        self,
        body: AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyBinding:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
            params=params,
            body=body,
        )

    def official_create_validating_webhook_configuration(
        self,
        body: AdmissionRegistrationV1ValidatingWebhookConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingWebhookConfiguration:
        _path = "/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1ValidatingWebhookConfiguration,
            params=params,
            body=body,
        )

    def official_replace_mutating_webhook_configuration(
        self,
        name: str,
        body: AdmissionRegistrationV1MutatingWebhookConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1MutatingWebhookConfiguration,
            params=params,
            body=body,
        )

    def official_replace_validating_admission_policy(
        self,
        name: str,
        body: AdmissionRegistrationV1ValidatingAdmissionPolicy,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
            body=body,
        )

    def official_replace_validating_admission_policy_status(
        self,
        name: str,
        body: AdmissionRegistrationV1ValidatingAdmissionPolicy,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicy:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicy,
            params=params,
            body=body,
        )

    def official_replace_validating_admission_policy_binding(
        self,
        name: str,
        body: AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1ValidatingAdmissionPolicyBinding,
            params=params,
            body=body,
        )

    def official_replace_validating_webhook_configuration(
        self,
        name: str,
        body: AdmissionRegistrationV1ValidatingWebhookConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1ValidatingWebhookConfiguration:
        _path = f"/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1ValidatingWebhookConfiguration,
            params=params,
            body=body,
        )

    def official_delete_collection_mutating_admission_policy(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_mutating_admission_policy(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = (
            f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies/{resource_name(name)}"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_collection_mutating_admission_policy_binding(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_mutating_admission_policy_binding(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_list_mutating_admission_policy(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyList:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyList,
            params=params,
        )

    def official_read_mutating_admission_policy(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicy:
        _path = (
            f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies/{resource_name(name)}"
        )
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicy,
            params=params,
        )

    def official_list_mutating_admission_policy_binding(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyBindingList:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyBindingList,
            params=params,
        )

    def official_read_mutating_admission_policy_binding(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
            params=params,
        )

    def watch_mutating_admission_policy_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/mutatingadmissionpolicies"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_mutating_admission_policy(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/mutatingadmissionpolicies/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_mutating_admission_policy_binding_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/admissionregistration.k8s.io/v1/watch/mutatingadmissionpolicybindings"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_mutating_admission_policy_binding(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/admissionregistration.k8s.io/v1/watch/mutatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def official_patch_mutating_admission_policy(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicy:
        _path = (
            f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies/{resource_name(name)}"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicy,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_mutating_admission_policy_binding(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_create_mutating_admission_policy(
        self,
        body: AdmissionRegistrationV1MutatingAdmissionPolicy,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicy:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicy,
            params=params,
            body=body,
        )

    def official_create_mutating_admission_policy_binding(
        self,
        body: AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyBinding:
        _path = "/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
            params=params,
            body=body,
        )

    def official_replace_mutating_admission_policy(
        self,
        name: str,
        body: AdmissionRegistrationV1MutatingAdmissionPolicy,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicy:
        _path = (
            f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicies/{resource_name(name)}"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicy,
            params=params,
            body=body,
        )

    def official_replace_mutating_admission_policy_binding(
        self,
        name: str,
        body: AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AdmissionRegistrationV1MutatingAdmissionPolicyBinding:
        _path = f"/apis/admissionregistration.k8s.io/v1/mutatingadmissionpolicybindings/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AdmissionRegistrationV1MutatingAdmissionPolicyBinding,
            params=params,
            body=body,
        )
