# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.server._sync import ServerAPI as ServerAPI
from httpx2_k8s.server._async import AsyncServerAPI as AsyncServerAPI

__all__ = ["AsyncServerAPI", "ServerAPI"]
