# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.server._async import AsyncServerAPI
from httpx2_k8s.server._sync import ServerAPI

__all__ = ["AsyncServerAPI", "ServerAPI"]
