# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "APIExtensionsV1API": "httpx2_k8s.apiextensions.v1._sync",
    "AsyncAPIExtensionsV1API": "httpx2_k8s.apiextensions.v1._async",
    "APIExtensionsV1CustomResourceColumnDefinition": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceConversion": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinition": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionCondition": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionList": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionNames": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionSpec": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionStatus": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceDefinitionVersion": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceSubresourceScale": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceSubresourceStatus": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceSubresources": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1CustomResourceValidation": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1ExternalDocumentation": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1JSON": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1JSONSchemaProps": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1JSONSchemaPropsOrArray": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1JSONSchemaPropsOrBool": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1JSONSchemaPropsOrStringArray": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1SelectableField": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1ServiceReference": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1ValidationRule": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1WebhookClientConfig": "httpx2_k8s.apiextensions.v1._models",
    "APIExtensionsV1WebhookConversion": "httpx2_k8s.apiextensions.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "APIExtensionsV1API",
    "APIExtensionsV1CustomResourceColumnDefinition",
    "APIExtensionsV1CustomResourceConversion",
    "APIExtensionsV1CustomResourceDefinition",
    "APIExtensionsV1CustomResourceDefinitionCondition",
    "APIExtensionsV1CustomResourceDefinitionList",
    "APIExtensionsV1CustomResourceDefinitionNames",
    "APIExtensionsV1CustomResourceDefinitionSpec",
    "APIExtensionsV1CustomResourceDefinitionStatus",
    "APIExtensionsV1CustomResourceDefinitionVersion",
    "APIExtensionsV1CustomResourceSubresourceScale",
    "APIExtensionsV1CustomResourceSubresourceStatus",
    "APIExtensionsV1CustomResourceSubresources",
    "APIExtensionsV1CustomResourceValidation",
    "APIExtensionsV1ExternalDocumentation",
    "APIExtensionsV1JSON",
    "APIExtensionsV1JSONSchemaProps",
    "APIExtensionsV1JSONSchemaPropsOrArray",
    "APIExtensionsV1JSONSchemaPropsOrBool",
    "APIExtensionsV1JSONSchemaPropsOrStringArray",
    "APIExtensionsV1SelectableField",
    "APIExtensionsV1ServiceReference",
    "APIExtensionsV1ValidationRule",
    "APIExtensionsV1WebhookClientConfig",
    "APIExtensionsV1WebhookConversion",
    "AsyncAPIExtensionsV1API",
]
