# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.networking.v1beta1._official_async import _OfficialNetworkingV1Beta1AsyncOperations


class AsyncNetworkingV1Beta1API(_OfficialNetworkingV1Beta1AsyncOperations):
    pass
