# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1Condition,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
)


class NetworkingV1Beta1IPAddress(KubeModel):
    api_version: Literal["networking.k8s.io/v1beta1"] = Field(
        default="networking.k8s.io/v1beta1", alias="apiVersion"
    )
    kind: Literal["IPAddress"] = Field(default="IPAddress", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1Beta1IPAddressSpec = Field(
        default_factory=lambda: NetworkingV1Beta1IPAddressSpec.model_construct(), alias="spec"
    )


class NetworkingV1Beta1IPAddressList(KubeModel):
    api_version: Literal["networking.k8s.io/v1beta1"] = Field(
        default="networking.k8s.io/v1beta1", alias="apiVersion"
    )
    items: list[NetworkingV1Beta1IPAddress] = Field(alias="items")
    kind: Literal["IPAddressList"] = Field(default="IPAddressList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1Beta1IPAddressSpec(KubeModel):
    parent_ref: NetworkingV1Beta1ParentReference = Field(alias="parentRef")


class NetworkingV1Beta1ParentReference(KubeModel):
    group: str | None = Field(default=None, alias="group")
    name: str = Field(alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    resource: str = Field(alias="resource")


class NetworkingV1Beta1ServiceCIDR(KubeModel):
    api_version: Literal["networking.k8s.io/v1beta1"] = Field(
        default="networking.k8s.io/v1beta1", alias="apiVersion"
    )
    kind: Literal["ServiceCIDR"] = Field(default="ServiceCIDR", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1Beta1ServiceCIDRSpec = Field(
        default_factory=lambda: NetworkingV1Beta1ServiceCIDRSpec.model_construct(), alias="spec"
    )
    status: NetworkingV1Beta1ServiceCIDRStatus = Field(
        default_factory=lambda: NetworkingV1Beta1ServiceCIDRStatus.model_construct(), alias="status"
    )


class NetworkingV1Beta1ServiceCIDRList(KubeModel):
    api_version: Literal["networking.k8s.io/v1beta1"] = Field(
        default="networking.k8s.io/v1beta1", alias="apiVersion"
    )
    items: list[NetworkingV1Beta1ServiceCIDR] = Field(alias="items")
    kind: Literal["ServiceCIDRList"] = Field(default="ServiceCIDRList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1Beta1ServiceCIDRSpec(KubeModel):
    cidrs: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="cidrs"
    )


class NetworkingV1Beta1ServiceCIDRStatus(KubeModel):
    conditions: list[MetaV1Condition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )


__all__ = [
    "NetworkingV1Beta1IPAddress",
    "NetworkingV1Beta1IPAddressList",
    "NetworkingV1Beta1IPAddressSpec",
    "NetworkingV1Beta1ParentReference",
    "NetworkingV1Beta1ServiceCIDR",
    "NetworkingV1Beta1ServiceCIDRList",
    "NetworkingV1Beta1ServiceCIDRSpec",
    "NetworkingV1Beta1ServiceCIDRStatus",
]
