# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.networking.v1beta1._official_sync import _OfficialNetworkingV1Beta1SyncOperations


class NetworkingV1Beta1API(_OfficialNetworkingV1Beta1SyncOperations):
    pass
