# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.coordination.v1beta1._async import AsyncCoordinationV1Beta1API
from httpx2_k8s.coordination.v1beta1._sync import CoordinationV1Beta1API

__all__ = ["AsyncCoordinationV1Beta1API", "CoordinationV1Beta1API"]
