# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1ListMeta,
    MetaV1MicroTime,
    MetaV1ObjectMeta,
)


class CoordinationV1Beta1LeaseCandidate(KubeModel):
    api_version: Literal["coordination.k8s.io/v1beta1"] = Field(
        default="coordination.k8s.io/v1beta1", alias="apiVersion"
    )
    kind: Literal["LeaseCandidate"] = Field(default="LeaseCandidate", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: CoordinationV1Beta1LeaseCandidateSpec = Field(
        default_factory=lambda: CoordinationV1Beta1LeaseCandidateSpec.model_construct(),
        alias="spec",
    )


class CoordinationV1Beta1LeaseCandidateList(KubeModel):
    api_version: Literal["coordination.k8s.io/v1beta1"] = Field(
        default="coordination.k8s.io/v1beta1", alias="apiVersion"
    )
    items: list[CoordinationV1Beta1LeaseCandidate] = Field(alias="items")
    kind: Literal["LeaseCandidateList"] = Field(default="LeaseCandidateList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class CoordinationV1Beta1LeaseCandidateSpec(KubeModel):
    binary_version: str = Field(default="", alias="binaryVersion")
    emulation_version: str | None = Field(default=None, alias="emulationVersion")
    lease_name: str = Field(default="", alias="leaseName")
    ping_time: MetaV1MicroTime | None = Field(default=None, alias="pingTime")
    renew_time: MetaV1MicroTime | None = Field(default=None, alias="renewTime")
    strategy: str = Field(alias="strategy")


__all__ = [
    "CoordinationV1Beta1LeaseCandidate",
    "CoordinationV1Beta1LeaseCandidateList",
    "CoordinationV1Beta1LeaseCandidateSpec",
]
