# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.coordination.v1beta1._official_sync import (
    _OfficialCoordinationV1Beta1SyncOperations,
)


class CoordinationV1Beta1API(_OfficialCoordinationV1Beta1SyncOperations):
    pass
