from __future__ import annotations

from importlib import import_module

_LAZY_IMPORTS = {
    "RBACV1API": "httpx2_k8s.rbac.v1",
    "APIError": "httpx2_k8s._errors",
    "APIGroup": "httpx2_k8s._models",
    "APIGroupList": "httpx2_k8s._models",
    "APIResource": "httpx2_k8s._models",
    "APIResourceList": "httpx2_k8s._models",
    "APIVersions": "httpx2_k8s._models",
    "AdmissionApplyConfiguration": "httpx2_k8s._models",
    "AdmissionAuditAnnotation": "httpx2_k8s._models",
    "AdmissionExpressionWarning": "httpx2_k8s._models",
    "AdmissionJSONPatch": "httpx2_k8s._models",
    "AdmissionMutation": "httpx2_k8s._models",
    "AdmissionPolicyCondition": "httpx2_k8s._models",
    "AdmissionRegistrationV1API": "httpx2_k8s.admissionregistration.v1",
    "AdmissionServiceReference": "httpx2_k8s._models",
    "AdmissionTypeChecking": "httpx2_k8s._models",
    "AdmissionValidation": "httpx2_k8s._models",
    "AdmissionVariable": "httpx2_k8s._models",
    "AggregationRule": "httpx2_k8s._models",
    "AppsV1API": "httpx2_k8s.apps.v1",
    "AsyncAdmissionRegistrationV1API": "httpx2_k8s.admissionregistration.v1",
    "AsyncAppsV1API": "httpx2_k8s.apps.v1",
    "AsyncAutoscalingV1API": "httpx2_k8s.autoscaling.v1",
    "AsyncAutoscalingV2API": "httpx2_k8s.autoscaling.v2",
    "AsyncBatchV1API": "httpx2_k8s.batch.v1",
    "AsyncCertificatesV1API": "httpx2_k8s.certificates.v1",
    "AsyncCoordinationV1API": "httpx2_k8s.coordination.v1",
    "AsyncCoreV1API": "httpx2_k8s.core.v1",
    "AsyncCustomObjectsAPI": "httpx2_k8s.custom_objects",
    "AsyncDiscoveryAPI": "httpx2_k8s.discovery",
    "AsyncDiscoveryV1API": "httpx2_k8s.discovery.v1",
    "AsyncKubeClient": "httpx2_k8s._async_client",
    "AsyncNetworkingV1API": "httpx2_k8s.networking.v1",
    "AsyncPolicyV1API": "httpx2_k8s.policy.v1",
    "AsyncPortForwardSession": "httpx2_k8s._port_forward",
    "AsyncRBACV1API": "httpx2_k8s.rbac.v1",
    "AsyncRemoteCommandSession": "httpx2_k8s._remote_command",
    "AsyncSchedulingV1API": "httpx2_k8s.scheduling.v1",
    "AsyncStorageV1API": "httpx2_k8s.storage.v1",
    "AutoscalingV1API": "httpx2_k8s.autoscaling.v1",
    "AutoscalingV2API": "httpx2_k8s.autoscaling.v2",
    "Base64Data": "httpx2_k8s._models",
    "BatchV1API": "httpx2_k8s.batch.v1",
    "Binding": "httpx2_k8s._models",
    "BoundObjectReference": "httpx2_k8s._models",
    "CSIDriver": "httpx2_k8s._models",
    "CSIDriverList": "httpx2_k8s._models",
    "CSIDriverSpec": "httpx2_k8s._models",
    "CSINode": "httpx2_k8s._models",
    "CSINodeDriver": "httpx2_k8s._models",
    "CSINodeList": "httpx2_k8s._models",
    "CSINodeSpec": "httpx2_k8s._models",
    "CSIStorageCapacity": "httpx2_k8s._models",
    "CSIStorageCapacityList": "httpx2_k8s._models",
    "CSITokenRequest": "httpx2_k8s._models",
    "CertificateSigningRequest": "httpx2_k8s._models",
    "CertificateSigningRequestCondition": "httpx2_k8s._models",
    "CertificateSigningRequestList": "httpx2_k8s._models",
    "CertificateSigningRequestSpec": "httpx2_k8s._models",
    "CertificateSigningRequestStatus": "httpx2_k8s._models",
    "CertificatesV1API": "httpx2_k8s.certificates.v1",
    "ClientConfig": "httpx2_k8s._config",
    "ClusterRole": "httpx2_k8s._models",
    "ClusterRoleBinding": "httpx2_k8s._models",
    "ClusterRoleBindingList": "httpx2_k8s._models",
    "ClusterRoleList": "httpx2_k8s._models",
    "ComponentCondition": "httpx2_k8s._models",
    "ComponentStatus": "httpx2_k8s._models",
    "ComponentStatusList": "httpx2_k8s._models",
    "Condition": "httpx2_k8s._models",
    "ConfigError": "httpx2_k8s._config",
    "ConfigMap": "httpx2_k8s._models",
    "ConfigMapList": "httpx2_k8s._models",
    "Container": "httpx2_k8s._models",
    "ContainerResizePolicy": "httpx2_k8s._models",
    "ContainerResourceMetricSource": "httpx2_k8s._models",
    "ContainerResourceMetricStatus": "httpx2_k8s._models",
    "ControllerRevision": "httpx2_k8s._models",
    "ControllerRevisionList": "httpx2_k8s._models",
    "CoordinationV1API": "httpx2_k8s.coordination.v1",
    "CoreV1API": "httpx2_k8s.core.v1",
    "CronJob": "httpx2_k8s._models",
    "CronJobList": "httpx2_k8s._models",
    "CronJobSpec": "httpx2_k8s._models",
    "CronJobStatus": "httpx2_k8s._models",
    "CrossVersionObjectReference": "httpx2_k8s._models",
    "CustomObjectSubresource": "httpx2_k8s.custom_objects",
    "CustomObjectsAPI": "httpx2_k8s.custom_objects",
    "CustomResource": "httpx2_k8s._models",
    "CustomResourceList": "httpx2_k8s._models",
    "DaemonEndpoint": "httpx2_k8s._models",
    "DaemonSet": "httpx2_k8s._models",
    "DaemonSetCondition": "httpx2_k8s._models",
    "DaemonSetList": "httpx2_k8s._models",
    "DaemonSetSpec": "httpx2_k8s._models",
    "DaemonSetStatus": "httpx2_k8s._models",
    "DaemonSetUpdateStrategy": "httpx2_k8s._models",
    "DeleteOptions": "httpx2_k8s._models",
    "DeleteResult": "httpx2_k8s._models",
    "Deployment": "httpx2_k8s._models",
    "DeploymentCondition": "httpx2_k8s._models",
    "DeploymentList": "httpx2_k8s._models",
    "DeploymentSpec": "httpx2_k8s._models",
    "DeploymentStatus": "httpx2_k8s._models",
    "DeploymentStrategy": "httpx2_k8s._models",
    "DiscoveryAPI": "httpx2_k8s.discovery",
    "DiscoveryEndpoint": "httpx2_k8s._models",
    "DiscoveryV1API": "httpx2_k8s.discovery.v1",
    "DryRun": "httpx2_k8s._patch",
    "EndpointAddress": "httpx2_k8s._models",
    "EndpointConditions": "httpx2_k8s._models",
    "EndpointHints": "httpx2_k8s._models",
    "EndpointPort": "httpx2_k8s._models",
    "EndpointSlice": "httpx2_k8s._models",
    "EndpointSliceList": "httpx2_k8s._models",
    "EndpointSlicePort": "httpx2_k8s._models",
    "EndpointSubset": "httpx2_k8s._models",
    "Endpoints": "httpx2_k8s._models",
    "EndpointsList": "httpx2_k8s._models",
    "EphemeralContainer": "httpx2_k8s._models",
    "Event": "httpx2_k8s._models",
    "EventList": "httpx2_k8s._models",
    "EventSeries": "httpx2_k8s._models",
    "EventSource": "httpx2_k8s._models",
    "Eviction": "httpx2_k8s._models",
    "ExternalMetricSource": "httpx2_k8s._models",
    "ExternalMetricStatus": "httpx2_k8s._models",
    "ForZone": "httpx2_k8s._models",
    "GroupVersionForDiscovery": "httpx2_k8s._models",
    "HPAScalingPolicy": "httpx2_k8s._models",
    "HPAScalingRules": "httpx2_k8s._models",
    "HTTPIngressPath": "httpx2_k8s._models",
    "HTTPIngressRuleValue": "httpx2_k8s._models",
    "HorizontalPodAutoscalerBehavior": "httpx2_k8s._models",
    "HorizontalPodAutoscalerCondition": "httpx2_k8s._models",
    "HorizontalPodAutoscalerListV1": "httpx2_k8s._models",
    "HorizontalPodAutoscalerListV2": "httpx2_k8s._models",
    "HorizontalPodAutoscalerSpecV1": "httpx2_k8s._models",
    "HorizontalPodAutoscalerSpecV2": "httpx2_k8s._models",
    "HorizontalPodAutoscalerStatusV1": "httpx2_k8s._models",
    "HorizontalPodAutoscalerStatusV2": "httpx2_k8s._models",
    "HorizontalPodAutoscalerV1": "httpx2_k8s._models",
    "HorizontalPodAutoscalerV2": "httpx2_k8s._models",
    "HostPathVolumeSource": "httpx2_k8s._models",
    "IPAddress": "httpx2_k8s._models",
    "IPAddressList": "httpx2_k8s._models",
    "IPAddressSpec": "httpx2_k8s._models",
    "IPBlock": "httpx2_k8s._models",
    "Ingress": "httpx2_k8s._models",
    "IngressBackend": "httpx2_k8s._models",
    "IngressClass": "httpx2_k8s._models",
    "IngressClassList": "httpx2_k8s._models",
    "IngressClassParametersReference": "httpx2_k8s._models",
    "IngressClassSpec": "httpx2_k8s._models",
    "IngressList": "httpx2_k8s._models",
    "IngressRule": "httpx2_k8s._models",
    "IngressServiceBackend": "httpx2_k8s._models",
    "IngressSpec": "httpx2_k8s._models",
    "IngressStatus": "httpx2_k8s._models",
    "IngressTLS": "httpx2_k8s._models",
    "Job": "httpx2_k8s._models",
    "JobCondition": "httpx2_k8s._models",
    "JobList": "httpx2_k8s._models",
    "JobSpec": "httpx2_k8s._models",
    "JobStatus": "httpx2_k8s._models",
    "JobTemplateSpec": "httpx2_k8s._models",
    "JsonPatch": "httpx2_k8s._models",
    "JsonPatchOperation": "httpx2_k8s._models",
    "KubeClient": "httpx2_k8s._client",
    "KubeModel": "httpx2_k8s._models",
    "LabelSelector": "httpx2_k8s._models",
    "LabelSelectorRequirement": "httpx2_k8s._models",
    "Lease": "httpx2_k8s._models",
    "LeaseList": "httpx2_k8s._models",
    "LeaseSpec": "httpx2_k8s._models",
    "LimitRange": "httpx2_k8s._models",
    "LimitRangeItem": "httpx2_k8s._models",
    "LimitRangeList": "httpx2_k8s._models",
    "LimitRangeSpec": "httpx2_k8s._models",
    "ListMeta": "httpx2_k8s._models",
    "LoadBalancerIngress": "httpx2_k8s._models",
    "LoadBalancerStatus": "httpx2_k8s._models",
    "LocalObjectReference": "httpx2_k8s._models",
    "MatchCondition": "httpx2_k8s._models",
    "MatchResources": "httpx2_k8s._models",
    "MergePatch": "httpx2_k8s._models",
    "MetricIdentifier": "httpx2_k8s._models",
    "MetricSpec": "httpx2_k8s._models",
    "MetricStatus": "httpx2_k8s._models",
    "MetricTarget": "httpx2_k8s._models",
    "MetricValueStatus": "httpx2_k8s._models",
    "MutatingAdmissionPolicy": "httpx2_k8s._models",
    "MutatingAdmissionPolicyBinding": "httpx2_k8s._models",
    "MutatingAdmissionPolicyBindingList": "httpx2_k8s._models",
    "MutatingAdmissionPolicyBindingSpec": "httpx2_k8s._models",
    "MutatingAdmissionPolicyList": "httpx2_k8s._models",
    "MutatingAdmissionPolicySpec": "httpx2_k8s._models",
    "MutatingWebhook": "httpx2_k8s._models",
    "MutatingWebhookConfiguration": "httpx2_k8s._models",
    "MutatingWebhookConfigurationList": "httpx2_k8s._models",
    "NamedRuleWithOperations": "httpx2_k8s._models",
    "Namespace": "httpx2_k8s._models",
    "NamespaceCondition": "httpx2_k8s._models",
    "NamespaceList": "httpx2_k8s._models",
    "NamespaceSpec": "httpx2_k8s._models",
    "NamespaceStatus": "httpx2_k8s._models",
    "NetworkPolicy": "httpx2_k8s._models",
    "NetworkPolicyEgressRule": "httpx2_k8s._models",
    "NetworkPolicyIngressRule": "httpx2_k8s._models",
    "NetworkPolicyList": "httpx2_k8s._models",
    "NetworkPolicyPeer": "httpx2_k8s._models",
    "NetworkPolicyPort": "httpx2_k8s._models",
    "NetworkPolicySpec": "httpx2_k8s._models",
    "NetworkingV1API": "httpx2_k8s.networking.v1",
    "Node": "httpx2_k8s._models",
    "NodeAddress": "httpx2_k8s._models",
    "NodeCondition": "httpx2_k8s._models",
    "NodeDaemonEndpoints": "httpx2_k8s._models",
    "NodeList": "httpx2_k8s._models",
    "NodeSpec": "httpx2_k8s._models",
    "NodeStatus": "httpx2_k8s._models",
    "NodeSystemInfo": "httpx2_k8s._models",
    "ObjectMeta": "httpx2_k8s._models",
    "ObjectMetricSource": "httpx2_k8s._models",
    "ObjectMetricStatus": "httpx2_k8s._models",
    "ObjectReference": "httpx2_k8s._models",
    "OpenAPIInfo": "httpx2_k8s._models",
    "OpenAPIV3Document": "httpx2_k8s._models",
    "OpenAPIV3GroupVersion": "httpx2_k8s._models",
    "OpenAPIV3Index": "httpx2_k8s._models",
    "Page": "httpx2_k8s.pagination",
    "PaginationError": "httpx2_k8s.pagination",
    "ParamKind": "httpx2_k8s._models",
    "ParamRef": "httpx2_k8s._models",
    "ParentReference": "httpx2_k8s._models",
    "PersistentVolume": "httpx2_k8s._models",
    "PersistentVolumeClaim": "httpx2_k8s._models",
    "PersistentVolumeClaimList": "httpx2_k8s._models",
    "PersistentVolumeClaimSpec": "httpx2_k8s._models",
    "PersistentVolumeClaimStatus": "httpx2_k8s._models",
    "PersistentVolumeList": "httpx2_k8s._models",
    "PersistentVolumeSpec": "httpx2_k8s._models",
    "PersistentVolumeStatus": "httpx2_k8s._models",
    "Pod": "httpx2_k8s._models",
    "PodDisruptionBudget": "httpx2_k8s._models",
    "PodDisruptionBudgetCondition": "httpx2_k8s._models",
    "PodDisruptionBudgetList": "httpx2_k8s._models",
    "PodDisruptionBudgetSpec": "httpx2_k8s._models",
    "PodDisruptionBudgetStatus": "httpx2_k8s._models",
    "PodList": "httpx2_k8s._models",
    "PodSpec": "httpx2_k8s._models",
    "PodStatus": "httpx2_k8s._models",
    "PodTemplate": "httpx2_k8s._models",
    "PodTemplateList": "httpx2_k8s._models",
    "PodTemplateSpec": "httpx2_k8s._models",
    "PodsMetricSource": "httpx2_k8s._models",
    "PodsMetricStatus": "httpx2_k8s._models",
    "PolicyRule": "httpx2_k8s._models",
    "PolicyV1API": "httpx2_k8s.policy.v1",
    "PortForwardError": "httpx2_k8s._port_forward",
    "PortForwardProtocolError": "httpx2_k8s._port_forward",
    "PortForwardSession": "httpx2_k8s._port_forward",
    "PortStatus": "httpx2_k8s._models",
    "Preconditions": "httpx2_k8s._models",
    "PriorityClass": "httpx2_k8s._models",
    "PriorityClassList": "httpx2_k8s._models",
    "RemoteCommandChannel": "httpx2_k8s._remote_command",
    "RemoteCommandFrame": "httpx2_k8s._remote_command",
    "RemoteCommandProtocolError": "httpx2_k8s._remote_command",
    "RemoteCommandResult": "httpx2_k8s._remote_command",
    "RemoteCommandSession": "httpx2_k8s._remote_command",
    "ReplicaSet": "httpx2_k8s._models",
    "ReplicaSetCondition": "httpx2_k8s._models",
    "ReplicaSetList": "httpx2_k8s._models",
    "ReplicaSetSpec": "httpx2_k8s._models",
    "ReplicaSetStatus": "httpx2_k8s._models",
    "ReplicationController": "httpx2_k8s._models",
    "ReplicationControllerCondition": "httpx2_k8s._models",
    "ReplicationControllerList": "httpx2_k8s._models",
    "ReplicationControllerSpec": "httpx2_k8s._models",
    "ReplicationControllerStatus": "httpx2_k8s._models",
    "ResourceMetricSource": "httpx2_k8s._models",
    "ResourceMetricStatus": "httpx2_k8s._models",
    "ResourceQuota": "httpx2_k8s._models",
    "ResourceQuotaList": "httpx2_k8s._models",
    "ResourceQuotaSpec": "httpx2_k8s._models",
    "ResourceQuotaStatus": "httpx2_k8s._models",
    "ResourceRequirements": "httpx2_k8s._models",
    "RetryPolicy": "httpx2_k8s._retry",
    "Role": "httpx2_k8s._models",
    "RoleBinding": "httpx2_k8s._models",
    "RoleBindingList": "httpx2_k8s._models",
    "RoleList": "httpx2_k8s._models",
    "RoleRef": "httpx2_k8s._models",
    "RollingUpdateDaemonSet": "httpx2_k8s._models",
    "RollingUpdateDeployment": "httpx2_k8s._models",
    "RollingUpdateStatefulSetStrategy": "httpx2_k8s._models",
    "RuleWithOperations": "httpx2_k8s._models",
    "Scale": "httpx2_k8s._models",
    "ScaleSpec": "httpx2_k8s._models",
    "ScaleStatus": "httpx2_k8s._models",
    "SchedulingV1API": "httpx2_k8s.scheduling.v1",
    "ScopeSelector": "httpx2_k8s._models",
    "ScopeSelectorRequirement": "httpx2_k8s._models",
    "Secret": "httpx2_k8s._models",
    "SecretList": "httpx2_k8s._models",
    "SecretValue": "httpx2_k8s._models",
    "ServerAddressByClientCIDR": "httpx2_k8s._models",
    "Service": "httpx2_k8s._models",
    "ServiceAccount": "httpx2_k8s._models",
    "ServiceAccountList": "httpx2_k8s._models",
    "ServiceBackendPort": "httpx2_k8s._models",
    "ServiceCIDR": "httpx2_k8s._models",
    "ServiceCIDRList": "httpx2_k8s._models",
    "ServiceCIDRSpec": "httpx2_k8s._models",
    "ServiceCIDRStatus": "httpx2_k8s._models",
    "ServiceList": "httpx2_k8s._models",
    "ServicePort": "httpx2_k8s._models",
    "ServiceSpec": "httpx2_k8s._models",
    "ServiceStatus": "httpx2_k8s._models",
    "StatefulSet": "httpx2_k8s._models",
    "StatefulSetCondition": "httpx2_k8s._models",
    "StatefulSetList": "httpx2_k8s._models",
    "StatefulSetPersistentVolumeClaimRetentionPolicy": "httpx2_k8s._models",
    "StatefulSetSpec": "httpx2_k8s._models",
    "StatefulSetStatus": "httpx2_k8s._models",
    "StatefulSetUpdateStrategy": "httpx2_k8s._models",
    "Status": "httpx2_k8s._models",
    "StatusCause": "httpx2_k8s._models",
    "StatusDetails": "httpx2_k8s._models",
    "StorageClass": "httpx2_k8s._models",
    "StorageClassList": "httpx2_k8s._models",
    "StorageV1API": "httpx2_k8s.storage.v1",
    "Subject": "httpx2_k8s._models",
    "Taint": "httpx2_k8s._models",
    "TokenRequest": "httpx2_k8s._models",
    "TokenRequestSpec": "httpx2_k8s._models",
    "TokenRequestStatus": "httpx2_k8s._models",
    "TokenValue": "httpx2_k8s._models",
    "TopologySelectorLabelRequirement": "httpx2_k8s._models",
    "TopologySelectorTerm": "httpx2_k8s._models",
    "TypedLocalObjectReference": "httpx2_k8s._models",
    "Unstructured": "httpx2_k8s._models",
    "UnstructuredList": "httpx2_k8s._models",
    "ValidatingAdmissionPolicy": "httpx2_k8s._models",
    "ValidatingAdmissionPolicyBinding": "httpx2_k8s._models",
    "ValidatingAdmissionPolicyBindingList": "httpx2_k8s._models",
    "ValidatingAdmissionPolicyBindingSpec": "httpx2_k8s._models",
    "ValidatingAdmissionPolicyList": "httpx2_k8s._models",
    "ValidatingAdmissionPolicySpec": "httpx2_k8s._models",
    "ValidatingAdmissionPolicyStatus": "httpx2_k8s._models",
    "ValidatingWebhook": "httpx2_k8s._models",
    "ValidatingWebhookConfiguration": "httpx2_k8s._models",
    "ValidatingWebhookConfigurationList": "httpx2_k8s._models",
    "VersionInfo": "httpx2_k8s._models",
    "VolumeAttachment": "httpx2_k8s._models",
    "VolumeAttachmentList": "httpx2_k8s._models",
    "VolumeAttachmentSource": "httpx2_k8s._models",
    "VolumeAttachmentSpec": "httpx2_k8s._models",
    "VolumeAttachmentStatus": "httpx2_k8s._models",
    "VolumeAttributesClass": "httpx2_k8s._models",
    "VolumeAttributesClassList": "httpx2_k8s._models",
    "VolumeError": "httpx2_k8s._models",
    "VolumeNodeResources": "httpx2_k8s._models",
    "VolumeResourceRequirements": "httpx2_k8s._models",
    "WatchBookmark": "httpx2_k8s._watch",
    "WatchError": "httpx2_k8s._watch",
    "WatchEvent": "httpx2_k8s._watch",
    "WatchProtocolError": "httpx2_k8s._watch",
    "WebhookClientConfig": "httpx2_k8s._models",
    "aiter_items": "httpx2_k8s.pagination",
    "aiter_pages": "httpx2_k8s.pagination",
    "iter_items": "httpx2_k8s.pagination",
    "iter_pages": "httpx2_k8s.pagination",
    "load_in_cluster_config": "httpx2_k8s._config",
    "load_kubeconfig": "httpx2_k8s._config",
    "load_kubeconfig_yaml": "httpx2_k8s._config",
}


def __getattr__(name: str) -> object:
    try:
        module_name = _LAZY_IMPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted((*globals(), *__all__))


__all__ = [
    "RBACV1API",
    "APIError",
    "APIGroup",
    "APIGroupList",
    "APIResource",
    "APIResourceList",
    "APIVersions",
    "AdmissionApplyConfiguration",
    "AdmissionAuditAnnotation",
    "AdmissionExpressionWarning",
    "AdmissionJSONPatch",
    "AdmissionMutation",
    "AdmissionPolicyCondition",
    "AdmissionRegistrationV1API",
    "AdmissionServiceReference",
    "AdmissionTypeChecking",
    "AdmissionValidation",
    "AdmissionVariable",
    "AggregationRule",
    "AppsV1API",
    "AsyncAdmissionRegistrationV1API",
    "AsyncAppsV1API",
    "AsyncAutoscalingV1API",
    "AsyncAutoscalingV2API",
    "AsyncBatchV1API",
    "AsyncCertificatesV1API",
    "AsyncCoordinationV1API",
    "AsyncCoreV1API",
    "AsyncCustomObjectsAPI",
    "AsyncDiscoveryAPI",
    "AsyncDiscoveryV1API",
    "AsyncKubeClient",
    "AsyncNetworkingV1API",
    "AsyncPolicyV1API",
    "AsyncPortForwardSession",
    "AsyncRBACV1API",
    "AsyncRemoteCommandSession",
    "AsyncSchedulingV1API",
    "AsyncStorageV1API",
    "AutoscalingV1API",
    "AutoscalingV2API",
    "Base64Data",
    "BatchV1API",
    "Binding",
    "BoundObjectReference",
    "CSIDriver",
    "CSIDriverList",
    "CSIDriverSpec",
    "CSINode",
    "CSINodeDriver",
    "CSINodeList",
    "CSINodeSpec",
    "CSIStorageCapacity",
    "CSIStorageCapacityList",
    "CSITokenRequest",
    "CertificateSigningRequest",
    "CertificateSigningRequestCondition",
    "CertificateSigningRequestList",
    "CertificateSigningRequestSpec",
    "CertificateSigningRequestStatus",
    "CertificatesV1API",
    "ClientConfig",
    "ClusterRole",
    "ClusterRoleBinding",
    "ClusterRoleBindingList",
    "ClusterRoleList",
    "ComponentCondition",
    "ComponentStatus",
    "ComponentStatusList",
    "Condition",
    "ConfigError",
    "ConfigMap",
    "ConfigMapList",
    "Container",
    "ContainerResizePolicy",
    "ContainerResourceMetricSource",
    "ContainerResourceMetricStatus",
    "ControllerRevision",
    "ControllerRevisionList",
    "CoordinationV1API",
    "CoreV1API",
    "CronJob",
    "CronJobList",
    "CronJobSpec",
    "CronJobStatus",
    "CrossVersionObjectReference",
    "CustomObjectSubresource",
    "CustomObjectsAPI",
    "CustomResource",
    "CustomResourceList",
    "DaemonEndpoint",
    "DaemonSet",
    "DaemonSetCondition",
    "DaemonSetList",
    "DaemonSetSpec",
    "DaemonSetStatus",
    "DaemonSetUpdateStrategy",
    "DeleteOptions",
    "DeleteResult",
    "Deployment",
    "DeploymentCondition",
    "DeploymentList",
    "DeploymentSpec",
    "DeploymentStatus",
    "DeploymentStrategy",
    "DiscoveryAPI",
    "DiscoveryEndpoint",
    "DiscoveryV1API",
    "DryRun",
    "EndpointAddress",
    "EndpointConditions",
    "EndpointHints",
    "EndpointPort",
    "EndpointSlice",
    "EndpointSliceList",
    "EndpointSlicePort",
    "EndpointSubset",
    "Endpoints",
    "EndpointsList",
    "EphemeralContainer",
    "Event",
    "EventList",
    "EventSeries",
    "EventSource",
    "Eviction",
    "ExternalMetricSource",
    "ExternalMetricStatus",
    "ForZone",
    "GroupVersionForDiscovery",
    "HPAScalingPolicy",
    "HPAScalingRules",
    "HTTPIngressPath",
    "HTTPIngressRuleValue",
    "HorizontalPodAutoscalerBehavior",
    "HorizontalPodAutoscalerCondition",
    "HorizontalPodAutoscalerListV1",
    "HorizontalPodAutoscalerListV2",
    "HorizontalPodAutoscalerSpecV1",
    "HorizontalPodAutoscalerSpecV2",
    "HorizontalPodAutoscalerStatusV1",
    "HorizontalPodAutoscalerStatusV2",
    "HorizontalPodAutoscalerV1",
    "HorizontalPodAutoscalerV2",
    "HostPathVolumeSource",
    "IPAddress",
    "IPAddressList",
    "IPAddressSpec",
    "IPBlock",
    "Ingress",
    "IngressBackend",
    "IngressClass",
    "IngressClassList",
    "IngressClassParametersReference",
    "IngressClassSpec",
    "IngressList",
    "IngressRule",
    "IngressServiceBackend",
    "IngressSpec",
    "IngressStatus",
    "IngressTLS",
    "Job",
    "JobCondition",
    "JobList",
    "JobSpec",
    "JobStatus",
    "JobTemplateSpec",
    "JsonPatch",
    "JsonPatchOperation",
    "KubeClient",
    "KubeModel",
    "LabelSelector",
    "LabelSelectorRequirement",
    "Lease",
    "LeaseList",
    "LeaseSpec",
    "LimitRange",
    "LimitRangeItem",
    "LimitRangeList",
    "LimitRangeSpec",
    "ListMeta",
    "LoadBalancerIngress",
    "LoadBalancerStatus",
    "LocalObjectReference",
    "MatchCondition",
    "MatchResources",
    "MergePatch",
    "MetricIdentifier",
    "MetricSpec",
    "MetricStatus",
    "MetricTarget",
    "MetricValueStatus",
    "MutatingAdmissionPolicy",
    "MutatingAdmissionPolicyBinding",
    "MutatingAdmissionPolicyBindingList",
    "MutatingAdmissionPolicyBindingSpec",
    "MutatingAdmissionPolicyList",
    "MutatingAdmissionPolicySpec",
    "MutatingWebhook",
    "MutatingWebhookConfiguration",
    "MutatingWebhookConfigurationList",
    "NamedRuleWithOperations",
    "Namespace",
    "NamespaceCondition",
    "NamespaceList",
    "NamespaceSpec",
    "NamespaceStatus",
    "NetworkPolicy",
    "NetworkPolicyEgressRule",
    "NetworkPolicyIngressRule",
    "NetworkPolicyList",
    "NetworkPolicyPeer",
    "NetworkPolicyPort",
    "NetworkPolicySpec",
    "NetworkingV1API",
    "Node",
    "NodeAddress",
    "NodeCondition",
    "NodeDaemonEndpoints",
    "NodeList",
    "NodeSpec",
    "NodeStatus",
    "NodeSystemInfo",
    "ObjectMeta",
    "ObjectMetricSource",
    "ObjectMetricStatus",
    "ObjectReference",
    "OpenAPIInfo",
    "OpenAPIV3Document",
    "OpenAPIV3GroupVersion",
    "OpenAPIV3Index",
    "Page",
    "PaginationError",
    "ParamKind",
    "ParamRef",
    "ParentReference",
    "PersistentVolume",
    "PersistentVolumeClaim",
    "PersistentVolumeClaimList",
    "PersistentVolumeClaimSpec",
    "PersistentVolumeClaimStatus",
    "PersistentVolumeList",
    "PersistentVolumeSpec",
    "PersistentVolumeStatus",
    "Pod",
    "PodDisruptionBudget",
    "PodDisruptionBudgetCondition",
    "PodDisruptionBudgetList",
    "PodDisruptionBudgetSpec",
    "PodDisruptionBudgetStatus",
    "PodList",
    "PodSpec",
    "PodStatus",
    "PodTemplate",
    "PodTemplateList",
    "PodTemplateSpec",
    "PodsMetricSource",
    "PodsMetricStatus",
    "PolicyRule",
    "PolicyV1API",
    "PortForwardError",
    "PortForwardProtocolError",
    "PortForwardSession",
    "PortStatus",
    "Preconditions",
    "PriorityClass",
    "PriorityClassList",
    "RemoteCommandChannel",
    "RemoteCommandFrame",
    "RemoteCommandProtocolError",
    "RemoteCommandResult",
    "RemoteCommandSession",
    "ReplicaSet",
    "ReplicaSetCondition",
    "ReplicaSetList",
    "ReplicaSetSpec",
    "ReplicaSetStatus",
    "ReplicationController",
    "ReplicationControllerCondition",
    "ReplicationControllerList",
    "ReplicationControllerSpec",
    "ReplicationControllerStatus",
    "ResourceMetricSource",
    "ResourceMetricStatus",
    "ResourceQuota",
    "ResourceQuotaList",
    "ResourceQuotaSpec",
    "ResourceQuotaStatus",
    "ResourceRequirements",
    "RetryPolicy",
    "Role",
    "RoleBinding",
    "RoleBindingList",
    "RoleList",
    "RoleRef",
    "RollingUpdateDaemonSet",
    "RollingUpdateDeployment",
    "RollingUpdateStatefulSetStrategy",
    "RuleWithOperations",
    "Scale",
    "ScaleSpec",
    "ScaleStatus",
    "SchedulingV1API",
    "ScopeSelector",
    "ScopeSelectorRequirement",
    "Secret",
    "SecretList",
    "SecretValue",
    "ServerAddressByClientCIDR",
    "Service",
    "ServiceAccount",
    "ServiceAccountList",
    "ServiceBackendPort",
    "ServiceCIDR",
    "ServiceCIDRList",
    "ServiceCIDRSpec",
    "ServiceCIDRStatus",
    "ServiceList",
    "ServicePort",
    "ServiceSpec",
    "ServiceStatus",
    "StatefulSet",
    "StatefulSetCondition",
    "StatefulSetList",
    "StatefulSetPersistentVolumeClaimRetentionPolicy",
    "StatefulSetSpec",
    "StatefulSetStatus",
    "StatefulSetUpdateStrategy",
    "Status",
    "StatusCause",
    "StatusDetails",
    "StorageClass",
    "StorageClassList",
    "StorageV1API",
    "Subject",
    "Taint",
    "TokenRequest",
    "TokenRequestSpec",
    "TokenRequestStatus",
    "TokenValue",
    "TopologySelectorLabelRequirement",
    "TopologySelectorTerm",
    "TypedLocalObjectReference",
    "Unstructured",
    "UnstructuredList",
    "ValidatingAdmissionPolicy",
    "ValidatingAdmissionPolicyBinding",
    "ValidatingAdmissionPolicyBindingList",
    "ValidatingAdmissionPolicyBindingSpec",
    "ValidatingAdmissionPolicyList",
    "ValidatingAdmissionPolicySpec",
    "ValidatingAdmissionPolicyStatus",
    "ValidatingWebhook",
    "ValidatingWebhookConfiguration",
    "ValidatingWebhookConfigurationList",
    "VersionInfo",
    "VolumeAttachment",
    "VolumeAttachmentList",
    "VolumeAttachmentSource",
    "VolumeAttachmentSpec",
    "VolumeAttachmentStatus",
    "VolumeAttributesClass",
    "VolumeAttributesClassList",
    "VolumeError",
    "VolumeNodeResources",
    "VolumeResourceRequirements",
    "WatchBookmark",
    "WatchError",
    "WatchEvent",
    "WatchProtocolError",
    "WebhookClientConfig",
    "aiter_items",
    "aiter_pages",
    "iter_items",
    "iter_pages",
    "load_in_cluster_config",
    "load_kubeconfig",
    "load_kubeconfig_yaml",
]
