# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from functools import cached_property
from typing import cast

from httpx2_k8s._protocols import AsyncKubeClientProtocol, SyncKubeClientProtocol
from httpx2_k8s.admissionregistration.v1alpha1 import (
    AdmissionRegistrationV1Alpha1API,
    AsyncAdmissionRegistrationV1Alpha1API,
)
from httpx2_k8s.admissionregistration.v1beta1 import (
    AdmissionRegistrationV1Beta1API,
    AsyncAdmissionRegistrationV1Beta1API,
)
from httpx2_k8s.apiextensions.v1 import (
    APIExtensionsV1API,
    AsyncAPIExtensionsV1API,
)
from httpx2_k8s.apiregistration.v1 import (
    APIRegistrationV1API,
    AsyncAPIRegistrationV1API,
)
from httpx2_k8s.authentication.v1 import (
    AuthenticationV1API,
    AsyncAuthenticationV1API,
)
from httpx2_k8s.authentication.v1alpha1 import (
    AuthenticationV1Alpha1API,
    AsyncAuthenticationV1Alpha1API,
)
from httpx2_k8s.authentication.v1beta1 import (
    AuthenticationV1Beta1API,
    AsyncAuthenticationV1Beta1API,
)
from httpx2_k8s.authorization.v1 import (
    AuthorizationV1API,
    AsyncAuthorizationV1API,
)
from httpx2_k8s.certificates.v1alpha1 import (
    CertificatesV1Alpha1API,
    AsyncCertificatesV1Alpha1API,
)
from httpx2_k8s.certificates.v1beta1 import (
    CertificatesV1Beta1API,
    AsyncCertificatesV1Beta1API,
)
from httpx2_k8s.coordination.v1alpha1 import (
    CoordinationV1Alpha1API,
    AsyncCoordinationV1Alpha1API,
)
from httpx2_k8s.coordination.v1alpha2 import (
    CoordinationV1Alpha2API,
    AsyncCoordinationV1Alpha2API,
)
from httpx2_k8s.coordination.v1beta1 import (
    CoordinationV1Beta1API,
    AsyncCoordinationV1Beta1API,
)
from httpx2_k8s.events.v1 import (
    EventsV1API,
    AsyncEventsV1API,
)
from httpx2_k8s.flowcontrol.v1 import (
    FlowControlV1API,
    AsyncFlowControlV1API,
)
from httpx2_k8s.flowcontrol.v1beta3 import (
    FlowControlV1Beta3API,
    AsyncFlowControlV1Beta3API,
)
from httpx2_k8s.internalapiserver.v1alpha1 import (
    InternalAPIServerV1Alpha1API,
    AsyncInternalAPIServerV1Alpha1API,
)
from httpx2_k8s.networking.v1beta1 import (
    NetworkingV1Beta1API,
    AsyncNetworkingV1Beta1API,
)
from httpx2_k8s.node.v1 import (
    NodeV1API,
    AsyncNodeV1API,
)
from httpx2_k8s.resource.v1 import (
    ResourceV1API,
    AsyncResourceV1API,
)
from httpx2_k8s.resource.v1alpha3 import (
    ResourceV1Alpha3API,
    AsyncResourceV1Alpha3API,
)
from httpx2_k8s.resource.v1beta1 import (
    ResourceV1Beta1API,
    AsyncResourceV1Beta1API,
)
from httpx2_k8s.resource.v1beta2 import (
    ResourceV1Beta2API,
    AsyncResourceV1Beta2API,
)
from httpx2_k8s.scheduling.v1alpha1 import (
    SchedulingV1Alpha1API,
    AsyncSchedulingV1Alpha1API,
)
from httpx2_k8s.scheduling.v1alpha2 import (
    SchedulingV1Alpha2API,
    AsyncSchedulingV1Alpha2API,
)
from httpx2_k8s.storage.v1alpha1 import (
    StorageV1Alpha1API,
    AsyncStorageV1Alpha1API,
)
from httpx2_k8s.storage.v1beta1 import (
    StorageV1Beta1API,
    AsyncStorageV1Beta1API,
)
from httpx2_k8s.storagemigration.v1alpha1 import (
    StorageMigrationV1Alpha1API,
    AsyncStorageMigrationV1Alpha1API,
)
from httpx2_k8s.storagemigration.v1beta1 import (
    StorageMigrationV1Beta1API,
    AsyncStorageMigrationV1Beta1API,
)
from httpx2_k8s.server import (
    ServerAPI,
    AsyncServerAPI,
)


class OfficialSyncClientAPIs:
    @cached_property
    def admissionregistration_v1alpha1(self) -> AdmissionRegistrationV1Alpha1API:
        return AdmissionRegistrationV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def admissionregistration_v1beta1(self) -> AdmissionRegistrationV1Beta1API:
        return AdmissionRegistrationV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def apiextensions_v1(self) -> APIExtensionsV1API:
        return APIExtensionsV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def apiregistration_v1(self) -> APIRegistrationV1API:
        return APIRegistrationV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1(self) -> AuthenticationV1API:
        return AuthenticationV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1alpha1(self) -> AuthenticationV1Alpha1API:
        return AuthenticationV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1beta1(self) -> AuthenticationV1Beta1API:
        return AuthenticationV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def authorization_v1(self) -> AuthorizationV1API:
        return AuthorizationV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def certificates_v1alpha1(self) -> CertificatesV1Alpha1API:
        return CertificatesV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def certificates_v1beta1(self) -> CertificatesV1Beta1API:
        return CertificatesV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1alpha1(self) -> CoordinationV1Alpha1API:
        return CoordinationV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1alpha2(self) -> CoordinationV1Alpha2API:
        return CoordinationV1Alpha2API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1beta1(self) -> CoordinationV1Beta1API:
        return CoordinationV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def events_v1(self) -> EventsV1API:
        return EventsV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def flowcontrol_v1(self) -> FlowControlV1API:
        return FlowControlV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def flowcontrol_v1beta3(self) -> FlowControlV1Beta3API:
        return FlowControlV1Beta3API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def internalapiserver_v1alpha1(self) -> InternalAPIServerV1Alpha1API:
        return InternalAPIServerV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def networking_v1beta1(self) -> NetworkingV1Beta1API:
        return NetworkingV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def node_v1(self) -> NodeV1API:
        return NodeV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def resource_v1(self) -> ResourceV1API:
        return ResourceV1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def resource_v1alpha3(self) -> ResourceV1Alpha3API:
        return ResourceV1Alpha3API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def resource_v1beta1(self) -> ResourceV1Beta1API:
        return ResourceV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def resource_v1beta2(self) -> ResourceV1Beta2API:
        return ResourceV1Beta2API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def scheduling_v1alpha1(self) -> SchedulingV1Alpha1API:
        return SchedulingV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def scheduling_v1alpha2(self) -> SchedulingV1Alpha2API:
        return SchedulingV1Alpha2API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def storage_v1alpha1(self) -> StorageV1Alpha1API:
        return StorageV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def storage_v1beta1(self) -> StorageV1Beta1API:
        return StorageV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def storagemigration_v1alpha1(self) -> StorageMigrationV1Alpha1API:
        return StorageMigrationV1Alpha1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def storagemigration_v1beta1(self) -> StorageMigrationV1Beta1API:
        return StorageMigrationV1Beta1API(cast(SyncKubeClientProtocol, self))

    @cached_property
    def server(self) -> ServerAPI:
        return ServerAPI(cast(SyncKubeClientProtocol, self))


class OfficialAsyncClientAPIs:
    @cached_property
    def admissionregistration_v1alpha1(self) -> AsyncAdmissionRegistrationV1Alpha1API:
        return AsyncAdmissionRegistrationV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def admissionregistration_v1beta1(self) -> AsyncAdmissionRegistrationV1Beta1API:
        return AsyncAdmissionRegistrationV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def apiextensions_v1(self) -> AsyncAPIExtensionsV1API:
        return AsyncAPIExtensionsV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def apiregistration_v1(self) -> AsyncAPIRegistrationV1API:
        return AsyncAPIRegistrationV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1(self) -> AsyncAuthenticationV1API:
        return AsyncAuthenticationV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1alpha1(self) -> AsyncAuthenticationV1Alpha1API:
        return AsyncAuthenticationV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def authentication_v1beta1(self) -> AsyncAuthenticationV1Beta1API:
        return AsyncAuthenticationV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def authorization_v1(self) -> AsyncAuthorizationV1API:
        return AsyncAuthorizationV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def certificates_v1alpha1(self) -> AsyncCertificatesV1Alpha1API:
        return AsyncCertificatesV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def certificates_v1beta1(self) -> AsyncCertificatesV1Beta1API:
        return AsyncCertificatesV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1alpha1(self) -> AsyncCoordinationV1Alpha1API:
        return AsyncCoordinationV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1alpha2(self) -> AsyncCoordinationV1Alpha2API:
        return AsyncCoordinationV1Alpha2API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def coordination_v1beta1(self) -> AsyncCoordinationV1Beta1API:
        return AsyncCoordinationV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def events_v1(self) -> AsyncEventsV1API:
        return AsyncEventsV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def flowcontrol_v1(self) -> AsyncFlowControlV1API:
        return AsyncFlowControlV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def flowcontrol_v1beta3(self) -> AsyncFlowControlV1Beta3API:
        return AsyncFlowControlV1Beta3API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def internalapiserver_v1alpha1(self) -> AsyncInternalAPIServerV1Alpha1API:
        return AsyncInternalAPIServerV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def networking_v1beta1(self) -> AsyncNetworkingV1Beta1API:
        return AsyncNetworkingV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def node_v1(self) -> AsyncNodeV1API:
        return AsyncNodeV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def resource_v1(self) -> AsyncResourceV1API:
        return AsyncResourceV1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def resource_v1alpha3(self) -> AsyncResourceV1Alpha3API:
        return AsyncResourceV1Alpha3API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def resource_v1beta1(self) -> AsyncResourceV1Beta1API:
        return AsyncResourceV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def resource_v1beta2(self) -> AsyncResourceV1Beta2API:
        return AsyncResourceV1Beta2API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def scheduling_v1alpha1(self) -> AsyncSchedulingV1Alpha1API:
        return AsyncSchedulingV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def scheduling_v1alpha2(self) -> AsyncSchedulingV1Alpha2API:
        return AsyncSchedulingV1Alpha2API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def storage_v1alpha1(self) -> AsyncStorageV1Alpha1API:
        return AsyncStorageV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def storage_v1beta1(self) -> AsyncStorageV1Beta1API:
        return AsyncStorageV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def storagemigration_v1alpha1(self) -> AsyncStorageMigrationV1Alpha1API:
        return AsyncStorageMigrationV1Alpha1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def storagemigration_v1beta1(self) -> AsyncStorageMigrationV1Beta1API:
        return AsyncStorageMigrationV1Beta1API(cast(AsyncKubeClientProtocol, self))

    @cached_property
    def server(self) -> AsyncServerAPI:
        return AsyncServerAPI(cast(AsyncKubeClientProtocol, self))
