# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.scheduling.v1alpha1._official_async import (
    _OfficialSchedulingV1Alpha1AsyncOperations,
)


class AsyncSchedulingV1Alpha1API(_OfficialSchedulingV1Alpha1AsyncOperations):
    pass
