# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import AsyncIterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_async_watch_response, query_parameters
from httpx2_k8s._protocols import AsyncKubeClientProtocol
from httpx2_k8s.apimachinery import (
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
)
from httpx2_k8s.scheduling.v1alpha1._models import (
    SchedulingV1Alpha1Workload,
    SchedulingV1Alpha1WorkloadList,
)


class _OfficialSchedulingV1Alpha1AsyncOperations:
    _client: AsyncKubeClientProtocol

    def __init__(self, client: AsyncKubeClientProtocol) -> None:
        self._client = client

    async def delete_collection_namespaced_workload(
        self,
        namespace: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_namespaced_workload(
        self,
        namespace: str,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/scheduling.k8s.io/v1alpha1/"
        params = {}
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    async def list_namespaced_workload(
        self,
        namespace: str,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> SchedulingV1Alpha1WorkloadList:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=SchedulingV1Alpha1WorkloadList,
            params=params,
        )

    async def read_namespaced_workload(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> SchedulingV1Alpha1Workload:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=SchedulingV1Alpha1Workload,
            params=params,
        )

    async def watch_namespaced_workload_list(
        self,
        namespace: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/watch/namespaces/{resource_name(namespace)}/workloads"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_namespaced_workload(
        self,
        namespace: str,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/watch/namespaces/{resource_name(namespace)}/workloads/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_workload_list_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/scheduling.k8s.io/v1alpha1/watch/workloads"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def list_workload_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> SchedulingV1Alpha1WorkloadList:
        _path = "/apis/scheduling.k8s.io/v1alpha1/workloads"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=SchedulingV1Alpha1WorkloadList,
            params=params,
        )

    async def patch_namespaced_workload(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> SchedulingV1Alpha1Workload:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=SchedulingV1Alpha1Workload,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def create_namespaced_workload(
        self,
        namespace: str,
        body: SchedulingV1Alpha1Workload,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> SchedulingV1Alpha1Workload:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=SchedulingV1Alpha1Workload,
            params=params,
            body=body,
        )

    async def replace_namespaced_workload(
        self,
        namespace: str,
        name: str,
        body: SchedulingV1Alpha1Workload,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> SchedulingV1Alpha1Workload:
        _path = f"/apis/scheduling.k8s.io/v1alpha1/namespaces/{resource_name(namespace)}/workloads/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=SchedulingV1Alpha1Workload,
            params=params,
            body=body,
        )
