# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.apiregistration.v1._async import AsyncAPIRegistrationV1API
from httpx2_k8s.apiregistration.v1._sync import APIRegistrationV1API

__all__ = ["APIRegistrationV1API", "AsyncAPIRegistrationV1API"]
