# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "APIRegistrationV1API": "httpx2_k8s.apiregistration.v1._sync",
    "AsyncAPIRegistrationV1API": "httpx2_k8s.apiregistration.v1._async",
    "APIRegistrationV1APIService": "httpx2_k8s.apiregistration.v1._models",
    "APIRegistrationV1APIServiceCondition": "httpx2_k8s.apiregistration.v1._models",
    "APIRegistrationV1APIServiceList": "httpx2_k8s.apiregistration.v1._models",
    "APIRegistrationV1APIServiceSpec": "httpx2_k8s.apiregistration.v1._models",
    "APIRegistrationV1APIServiceStatus": "httpx2_k8s.apiregistration.v1._models",
    "APIRegistrationV1ServiceReference": "httpx2_k8s.apiregistration.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "APIRegistrationV1API",
    "APIRegistrationV1APIService",
    "APIRegistrationV1APIServiceCondition",
    "APIRegistrationV1APIServiceList",
    "APIRegistrationV1APIServiceSpec",
    "APIRegistrationV1APIServiceStatus",
    "APIRegistrationV1ServiceReference",
    "AsyncAPIRegistrationV1API",
]
