# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.apiregistration.v1._sync import APIRegistrationV1API as APIRegistrationV1API
from httpx2_k8s.apiregistration.v1._async import (
    AsyncAPIRegistrationV1API as AsyncAPIRegistrationV1API,
)
from httpx2_k8s.apiregistration.v1._models import (
    APIRegistrationV1APIService as APIRegistrationV1APIService,
    APIRegistrationV1APIServiceCondition as APIRegistrationV1APIServiceCondition,
    APIRegistrationV1APIServiceList as APIRegistrationV1APIServiceList,
    APIRegistrationV1APIServiceSpec as APIRegistrationV1APIServiceSpec,
    APIRegistrationV1APIServiceStatus as APIRegistrationV1APIServiceStatus,
    APIRegistrationV1ServiceReference as APIRegistrationV1ServiceReference,
)

__all__ = [
    "APIRegistrationV1API",
    "APIRegistrationV1APIService",
    "APIRegistrationV1APIServiceCondition",
    "APIRegistrationV1APIServiceList",
    "APIRegistrationV1APIServiceSpec",
    "APIRegistrationV1APIServiceStatus",
    "APIRegistrationV1ServiceReference",
    "AsyncAPIRegistrationV1API",
]
