# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.events.v1._sync import EventsV1API as EventsV1API
from httpx2_k8s.events.v1._async import AsyncEventsV1API as AsyncEventsV1API
from httpx2_k8s.events.v1._models import (
    EventsV1Event as EventsV1Event,
    EventsV1EventList as EventsV1EventList,
    EventsV1EventSeries as EventsV1EventSeries,
)

__all__ = [
    "AsyncEventsV1API",
    "EventsV1API",
    "EventsV1Event",
    "EventsV1EventList",
    "EventsV1EventSeries",
]
