# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.events.v1._official_sync import _OfficialEventsV1SyncOperations


class EventsV1API(_OfficialEventsV1SyncOperations):
    pass
