# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "AuthorizationV1API": "httpx2_k8s.authorization.v1._sync",
    "AsyncAuthorizationV1API": "httpx2_k8s.authorization.v1._async",
    "AuthorizationV1FieldSelectorAttributes": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1LabelSelectorAttributes": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1LocalSubjectAccessReview": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1NonResourceAttributes": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1NonResourceRule": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1ResourceAttributes": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1ResourceRule": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SelfSubjectAccessReview": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SelfSubjectAccessReviewSpec": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SelfSubjectRulesReview": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SelfSubjectRulesReviewSpec": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SubjectAccessReview": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SubjectAccessReviewSpec": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SubjectAccessReviewStatus": "httpx2_k8s.authorization.v1._models",
    "AuthorizationV1SubjectRulesReviewStatus": "httpx2_k8s.authorization.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncAuthorizationV1API",
    "AuthorizationV1API",
    "AuthorizationV1FieldSelectorAttributes",
    "AuthorizationV1LabelSelectorAttributes",
    "AuthorizationV1LocalSubjectAccessReview",
    "AuthorizationV1NonResourceAttributes",
    "AuthorizationV1NonResourceRule",
    "AuthorizationV1ResourceAttributes",
    "AuthorizationV1ResourceRule",
    "AuthorizationV1SelfSubjectAccessReview",
    "AuthorizationV1SelfSubjectAccessReviewSpec",
    "AuthorizationV1SelfSubjectRulesReview",
    "AuthorizationV1SelfSubjectRulesReviewSpec",
    "AuthorizationV1SubjectAccessReview",
    "AuthorizationV1SubjectAccessReviewSpec",
    "AuthorizationV1SubjectAccessReviewStatus",
    "AuthorizationV1SubjectRulesReviewStatus",
]
