# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.authorization.v1._sync import AuthorizationV1API as AuthorizationV1API
from httpx2_k8s.authorization.v1._async import AsyncAuthorizationV1API as AsyncAuthorizationV1API
from httpx2_k8s.authorization.v1._models import (
    AuthorizationV1FieldSelectorAttributes as AuthorizationV1FieldSelectorAttributes,
    AuthorizationV1LabelSelectorAttributes as AuthorizationV1LabelSelectorAttributes,
    AuthorizationV1LocalSubjectAccessReview as AuthorizationV1LocalSubjectAccessReview,
    AuthorizationV1NonResourceAttributes as AuthorizationV1NonResourceAttributes,
    AuthorizationV1NonResourceRule as AuthorizationV1NonResourceRule,
    AuthorizationV1ResourceAttributes as AuthorizationV1ResourceAttributes,
    AuthorizationV1ResourceRule as AuthorizationV1ResourceRule,
    AuthorizationV1SelfSubjectAccessReview as AuthorizationV1SelfSubjectAccessReview,
    AuthorizationV1SelfSubjectAccessReviewSpec as AuthorizationV1SelfSubjectAccessReviewSpec,
    AuthorizationV1SelfSubjectRulesReview as AuthorizationV1SelfSubjectRulesReview,
    AuthorizationV1SelfSubjectRulesReviewSpec as AuthorizationV1SelfSubjectRulesReviewSpec,
    AuthorizationV1SubjectAccessReview as AuthorizationV1SubjectAccessReview,
    AuthorizationV1SubjectAccessReviewSpec as AuthorizationV1SubjectAccessReviewSpec,
    AuthorizationV1SubjectAccessReviewStatus as AuthorizationV1SubjectAccessReviewStatus,
    AuthorizationV1SubjectRulesReviewStatus as AuthorizationV1SubjectRulesReviewStatus,
)

__all__ = [
    "AsyncAuthorizationV1API",
    "AuthorizationV1API",
    "AuthorizationV1FieldSelectorAttributes",
    "AuthorizationV1LabelSelectorAttributes",
    "AuthorizationV1LocalSubjectAccessReview",
    "AuthorizationV1NonResourceAttributes",
    "AuthorizationV1NonResourceRule",
    "AuthorizationV1ResourceAttributes",
    "AuthorizationV1ResourceRule",
    "AuthorizationV1SelfSubjectAccessReview",
    "AuthorizationV1SelfSubjectAccessReviewSpec",
    "AuthorizationV1SelfSubjectRulesReview",
    "AuthorizationV1SelfSubjectRulesReviewSpec",
    "AuthorizationV1SubjectAccessReview",
    "AuthorizationV1SubjectAccessReviewSpec",
    "AuthorizationV1SubjectAccessReviewStatus",
    "AuthorizationV1SubjectRulesReviewStatus",
]
