# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.authorization.v1._official_async import _OfficialAuthorizationV1AsyncOperations


class AsyncAuthorizationV1API(_OfficialAuthorizationV1AsyncOperations):
    pass
