# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1FieldSelectorRequirement,
    MetaV1LabelSelectorRequirement,
    MetaV1ObjectMeta,
)


class AuthorizationV1FieldSelectorAttributes(KubeModel):
    raw_selector: str | None = Field(default=None, alias="rawSelector")
    requirements: list[MetaV1FieldSelectorRequirement] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="requirements"
    )


class AuthorizationV1LabelSelectorAttributes(KubeModel):
    raw_selector: str | None = Field(default=None, alias="rawSelector")
    requirements: list[MetaV1LabelSelectorRequirement] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="requirements"
    )


class AuthorizationV1LocalSubjectAccessReview(KubeModel):
    api_version: Literal["authorization.k8s.io/v1"] = Field(
        default="authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["LocalSubjectAccessReview"] = Field(
        default="LocalSubjectAccessReview", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AuthorizationV1SubjectAccessReviewSpec = Field(
        default_factory=lambda: AuthorizationV1SubjectAccessReviewSpec.model_construct(),
        alias="spec",
    )
    status: AuthorizationV1SubjectAccessReviewStatus = Field(
        default_factory=lambda: AuthorizationV1SubjectAccessReviewStatus.model_construct(),
        alias="status",
    )


class AuthorizationV1NonResourceAttributes(KubeModel):
    path: str | None = Field(default=None, alias="path")
    verb: str | None = Field(default=None, alias="verb")


class AuthorizationV1NonResourceRule(KubeModel):
    non_resource_ur_ls: list[str] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="nonResourceURLs",
    )
    verbs: list[str] = Field(json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="verbs")


class AuthorizationV1ResourceAttributes(KubeModel):
    field_selector: AuthorizationV1FieldSelectorAttributes | None = Field(
        default=None, alias="fieldSelector"
    )
    group: str | None = Field(default=None, alias="group")
    label_selector: AuthorizationV1LabelSelectorAttributes | None = Field(
        default=None, alias="labelSelector"
    )
    name: str | None = Field(default=None, alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    resource: str | None = Field(default=None, alias="resource")
    subresource: str | None = Field(default=None, alias="subresource")
    verb: str | None = Field(default=None, alias="verb")
    version: str | None = Field(default=None, alias="version")


class AuthorizationV1ResourceRule(KubeModel):
    api_groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiGroups"
    )
    resource_names: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceNames"
    )
    resources: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resources"
    )
    verbs: list[str] = Field(json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="verbs")


class AuthorizationV1SelfSubjectAccessReview(KubeModel):
    api_version: Literal["authorization.k8s.io/v1"] = Field(
        default="authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["SelfSubjectAccessReview"] = Field(
        default="SelfSubjectAccessReview", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AuthorizationV1SelfSubjectAccessReviewSpec = Field(
        default_factory=lambda: AuthorizationV1SelfSubjectAccessReviewSpec.model_construct(),
        alias="spec",
    )
    status: AuthorizationV1SubjectAccessReviewStatus = Field(
        default_factory=lambda: AuthorizationV1SubjectAccessReviewStatus.model_construct(),
        alias="status",
    )


class AuthorizationV1SelfSubjectAccessReviewSpec(KubeModel):
    non_resource_attributes: AuthorizationV1NonResourceAttributes | None = Field(
        default=None, alias="nonResourceAttributes"
    )
    resource_attributes: AuthorizationV1ResourceAttributes | None = Field(
        default=None, alias="resourceAttributes"
    )


class AuthorizationV1SelfSubjectRulesReview(KubeModel):
    api_version: Literal["authorization.k8s.io/v1"] = Field(
        default="authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["SelfSubjectRulesReview"] = Field(default="SelfSubjectRulesReview", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AuthorizationV1SelfSubjectRulesReviewSpec = Field(
        default_factory=lambda: AuthorizationV1SelfSubjectRulesReviewSpec.model_construct(),
        alias="spec",
    )
    status: AuthorizationV1SubjectRulesReviewStatus = Field(
        default_factory=lambda: AuthorizationV1SubjectRulesReviewStatus.model_construct(),
        alias="status",
    )


class AuthorizationV1SelfSubjectRulesReviewSpec(KubeModel):
    namespace: str | None = Field(default=None, alias="namespace")


class AuthorizationV1SubjectAccessReview(KubeModel):
    api_version: Literal["authorization.k8s.io/v1"] = Field(
        default="authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["SubjectAccessReview"] = Field(default="SubjectAccessReview", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AuthorizationV1SubjectAccessReviewSpec = Field(
        default_factory=lambda: AuthorizationV1SubjectAccessReviewSpec.model_construct(),
        alias="spec",
    )
    status: AuthorizationV1SubjectAccessReviewStatus = Field(
        default_factory=lambda: AuthorizationV1SubjectAccessReviewStatus.model_construct(),
        alias="status",
    )


class AuthorizationV1SubjectAccessReviewSpec(KubeModel):
    extra: dict[str, list[str]] | None = Field(default=None, alias="extra")
    groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="groups"
    )
    non_resource_attributes: AuthorizationV1NonResourceAttributes | None = Field(
        default=None, alias="nonResourceAttributes"
    )
    resource_attributes: AuthorizationV1ResourceAttributes | None = Field(
        default=None, alias="resourceAttributes"
    )
    uid: str | None = Field(default=None, alias="uid")
    user: str | None = Field(default=None, alias="user")


class AuthorizationV1SubjectAccessReviewStatus(KubeModel):
    allowed: bool = Field(default=False, alias="allowed")
    denied: bool | None = Field(default=None, alias="denied")
    evaluation_error: str | None = Field(default=None, alias="evaluationError")
    reason: str | None = Field(default=None, alias="reason")


class AuthorizationV1SubjectRulesReviewStatus(KubeModel):
    evaluation_error: str | None = Field(default=None, alias="evaluationError")
    incomplete: bool = Field(default=False, alias="incomplete")
    non_resource_rules: list[AuthorizationV1NonResourceRule] = Field(
        json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="nonResourceRules"
    )
    resource_rules: list[AuthorizationV1ResourceRule] = Field(
        json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceRules"
    )


__all__ = [
    "AuthorizationV1FieldSelectorAttributes",
    "AuthorizationV1LabelSelectorAttributes",
    "AuthorizationV1LocalSubjectAccessReview",
    "AuthorizationV1NonResourceAttributes",
    "AuthorizationV1NonResourceRule",
    "AuthorizationV1ResourceAttributes",
    "AuthorizationV1ResourceRule",
    "AuthorizationV1SelfSubjectAccessReview",
    "AuthorizationV1SelfSubjectAccessReviewSpec",
    "AuthorizationV1SelfSubjectRulesReview",
    "AuthorizationV1SelfSubjectRulesReviewSpec",
    "AuthorizationV1SubjectAccessReview",
    "AuthorizationV1SubjectAccessReviewSpec",
    "AuthorizationV1SubjectAccessReviewStatus",
    "AuthorizationV1SubjectRulesReviewStatus",
]
