# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.node.v1._official_async import _OfficialNodeV1AsyncOperations


class AsyncNodeV1API(_OfficialNodeV1AsyncOperations):
    pass
