# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Iterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_watch_response, query_parameters
from httpx2_k8s._protocols import SyncKubeClientProtocol
from httpx2_k8s.apimachinery import (
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
)
from httpx2_k8s.node.v1._models import (
    NodeV1RuntimeClass,
    NodeV1RuntimeClassList,
)


class _OfficialNodeV1SyncOperations:
    _client: SyncKubeClientProtocol

    def __init__(self, client: SyncKubeClientProtocol) -> None:
        self._client = client

    def delete_collection_runtime_class(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/node.k8s.io/v1/runtimeclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def delete_runtime_class(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/node.k8s.io/v1/runtimeclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/node.k8s.io/v1/"
        params = {}
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    def list_runtime_class(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> NodeV1RuntimeClassList:
        _path = "/apis/node.k8s.io/v1/runtimeclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=NodeV1RuntimeClassList,
            params=params,
        )

    def read_runtime_class(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> NodeV1RuntimeClass:
        _path = f"/apis/node.k8s.io/v1/runtimeclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=NodeV1RuntimeClass,
            params=params,
        )

    def watch_runtime_class_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/node.k8s.io/v1/watch/runtimeclasses"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_runtime_class(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/node.k8s.io/v1/watch/runtimeclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def patch_runtime_class(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> NodeV1RuntimeClass:
        _path = f"/apis/node.k8s.io/v1/runtimeclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=NodeV1RuntimeClass,
            params=params,
            body=body,
            content_type=content_type,
        )

    def create_runtime_class(
        self,
        body: NodeV1RuntimeClass,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> NodeV1RuntimeClass:
        _path = "/apis/node.k8s.io/v1/runtimeclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=NodeV1RuntimeClass,
            params=params,
            body=body,
        )

    def replace_runtime_class(
        self,
        name: str,
        body: NodeV1RuntimeClass,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> NodeV1RuntimeClass:
        _path = f"/apis/node.k8s.io/v1/runtimeclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=NodeV1RuntimeClass,
            params=params,
            body=body,
        )
