# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "RBACV1API": "httpx2_k8s.rbac.v1._facade",
    "AsyncRBACV1API": "httpx2_k8s.rbac.v1._facade",
    "RbacV1AggregationRule": "httpx2_k8s.rbac.v1._models",
    "RbacV1ClusterRole": "httpx2_k8s.rbac.v1._models",
    "RbacV1ClusterRoleBinding": "httpx2_k8s.rbac.v1._models",
    "RbacV1ClusterRoleBindingList": "httpx2_k8s.rbac.v1._models",
    "RbacV1ClusterRoleList": "httpx2_k8s.rbac.v1._models",
    "RbacV1PolicyRule": "httpx2_k8s.rbac.v1._models",
    "RbacV1Role": "httpx2_k8s.rbac.v1._models",
    "RbacV1RoleBinding": "httpx2_k8s.rbac.v1._models",
    "RbacV1RoleBindingList": "httpx2_k8s.rbac.v1._models",
    "RbacV1RoleList": "httpx2_k8s.rbac.v1._models",
    "RbacV1RoleRef": "httpx2_k8s.rbac.v1._models",
    "RbacV1Subject": "httpx2_k8s.rbac.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncRBACV1API",
    "RBACV1API",
    "RbacV1AggregationRule",
    "RbacV1ClusterRole",
    "RbacV1ClusterRoleBinding",
    "RbacV1ClusterRoleBindingList",
    "RbacV1ClusterRoleList",
    "RbacV1PolicyRule",
    "RbacV1Role",
    "RbacV1RoleBinding",
    "RbacV1RoleBindingList",
    "RbacV1RoleList",
    "RbacV1RoleRef",
    "RbacV1Subject",
]
