# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s.rbac.v1._facade import RBACV1API as RBACV1API
from httpx2_k8s.rbac.v1._facade import AsyncRBACV1API as AsyncRBACV1API
from httpx2_k8s.rbac.v1._models import (
    RbacV1AggregationRule as RbacV1AggregationRule,
    RbacV1ClusterRole as RbacV1ClusterRole,
    RbacV1ClusterRoleBinding as RbacV1ClusterRoleBinding,
    RbacV1ClusterRoleBindingList as RbacV1ClusterRoleBindingList,
    RbacV1ClusterRoleList as RbacV1ClusterRoleList,
    RbacV1PolicyRule as RbacV1PolicyRule,
    RbacV1Role as RbacV1Role,
    RbacV1RoleBinding as RbacV1RoleBinding,
    RbacV1RoleBindingList as RbacV1RoleBindingList,
    RbacV1RoleList as RbacV1RoleList,
    RbacV1RoleRef as RbacV1RoleRef,
    RbacV1Subject as RbacV1Subject,
)

__all__ = [
    "AsyncRBACV1API",
    "RBACV1API",
    "RbacV1AggregationRule",
    "RbacV1ClusterRole",
    "RbacV1ClusterRoleBinding",
    "RbacV1ClusterRoleBindingList",
    "RbacV1ClusterRoleList",
    "RbacV1PolicyRule",
    "RbacV1Role",
    "RbacV1RoleBinding",
    "RbacV1RoleBindingList",
    "RbacV1RoleList",
    "RbacV1RoleRef",
    "RbacV1Subject",
]
