# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.rbac.v1._async import AsyncRBACV1API as _ExistingAsyncAPI
from httpx2_k8s.rbac.v1._official_async import _OfficialRBACV1AsyncOperations
from httpx2_k8s.rbac.v1._official_sync import _OfficialRBACV1SyncOperations
from httpx2_k8s.rbac.v1._sync import RBACV1API as _ExistingSyncAPI


class RBACV1API(_ExistingSyncAPI, _OfficialRBACV1SyncOperations):
    pass


class AsyncRBACV1API(_ExistingAsyncAPI, _OfficialRBACV1AsyncOperations):
    pass
