# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1LabelSelector,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
)


class RbacV1AggregationRule(KubeModel):
    cluster_role_selectors: list[MetaV1LabelSelector] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="clusterRoleSelectors",
    )


class RbacV1ClusterRole(KubeModel):
    aggregation_rule: RbacV1AggregationRule | None = Field(default=None, alias="aggregationRule")
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ClusterRole"] = Field(default="ClusterRole", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    rules: list[RbacV1PolicyRule] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="rules"
    )


class RbacV1ClusterRoleBinding(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ClusterRoleBinding"] = Field(default="ClusterRoleBinding", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    role_ref: RbacV1RoleRef = Field(
        default_factory=lambda: RbacV1RoleRef.model_construct(), alias="roleRef"
    )
    subjects: list[RbacV1Subject] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="subjects"
    )


class RbacV1ClusterRoleBindingList(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    items: list[RbacV1ClusterRoleBinding] = Field(alias="items")
    kind: Literal["ClusterRoleBindingList"] = Field(default="ClusterRoleBindingList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class RbacV1ClusterRoleList(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    items: list[RbacV1ClusterRole] = Field(alias="items")
    kind: Literal["ClusterRoleList"] = Field(default="ClusterRoleList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class RbacV1PolicyRule(KubeModel):
    api_groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiGroups"
    )
    non_resource_ur_ls: list[str] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="nonResourceURLs",
    )
    resource_names: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceNames"
    )
    resources: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resources"
    )
    verbs: list[str] = Field(json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="verbs")


class RbacV1Role(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["Role"] = Field(default="Role", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    rules: list[RbacV1PolicyRule] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="rules"
    )


class RbacV1RoleBinding(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["RoleBinding"] = Field(default="RoleBinding", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    role_ref: RbacV1RoleRef = Field(
        default_factory=lambda: RbacV1RoleRef.model_construct(), alias="roleRef"
    )
    subjects: list[RbacV1Subject] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="subjects"
    )


class RbacV1RoleBindingList(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    items: list[RbacV1RoleBinding] = Field(alias="items")
    kind: Literal["RoleBindingList"] = Field(default="RoleBindingList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class RbacV1RoleList(KubeModel):
    api_version: Literal["rbac.authorization.k8s.io/v1"] = Field(
        default="rbac.authorization.k8s.io/v1", alias="apiVersion"
    )
    items: list[RbacV1Role] = Field(alias="items")
    kind: Literal["RoleList"] = Field(default="RoleList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class RbacV1RoleRef(KubeModel):
    api_group: str = Field(default="", alias="apiGroup")
    kind: str = Field(default="", alias="kind")
    name: str = Field(default="", alias="name")


class RbacV1Subject(KubeModel):
    api_group: str | None = Field(default=None, alias="apiGroup")
    kind: str = Field(default="", alias="kind")
    name: str = Field(default="", alias="name")
    namespace: str | None = Field(default=None, alias="namespace")


__all__ = [
    "RbacV1AggregationRule",
    "RbacV1ClusterRole",
    "RbacV1ClusterRoleBinding",
    "RbacV1ClusterRoleBindingList",
    "RbacV1ClusterRoleList",
    "RbacV1PolicyRule",
    "RbacV1Role",
    "RbacV1RoleBinding",
    "RbacV1RoleBindingList",
    "RbacV1RoleList",
    "RbacV1RoleRef",
    "RbacV1Subject",
]
