# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.resource.v1alpha3._async import AsyncResourceV1Alpha3API
from httpx2_k8s.resource.v1alpha3._sync import ResourceV1Alpha3API

__all__ = ["AsyncResourceV1Alpha3API", "ResourceV1Alpha3API"]
