# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1ListMeta,
    MetaV1MicroTime,
    MetaV1ObjectMeta,
)


class CoordinationV1Lease(KubeModel):
    api_version: Literal["coordination.k8s.io/v1"] = Field(
        default="coordination.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["Lease"] = Field(default="Lease", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: CoordinationV1LeaseSpec = Field(
        default_factory=lambda: CoordinationV1LeaseSpec.model_construct(), alias="spec"
    )


class CoordinationV1LeaseList(KubeModel):
    api_version: Literal["coordination.k8s.io/v1"] = Field(
        default="coordination.k8s.io/v1", alias="apiVersion"
    )
    items: list[CoordinationV1Lease] = Field(alias="items")
    kind: Literal["LeaseList"] = Field(default="LeaseList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class CoordinationV1LeaseSpec(KubeModel):
    acquire_time: MetaV1MicroTime | None = Field(default=None, alias="acquireTime")
    holder_identity: str | None = Field(default=None, alias="holderIdentity")
    lease_duration_seconds: int | None = Field(default=None, alias="leaseDurationSeconds")
    lease_transitions: int | None = Field(default=None, alias="leaseTransitions")
    preferred_holder: str | None = Field(default=None, alias="preferredHolder")
    renew_time: MetaV1MicroTime | None = Field(default=None, alias="renewTime")
    strategy: str | None = Field(default=None, alias="strategy")


__all__ = [
    "CoordinationV1Lease",
    "CoordinationV1LeaseList",
    "CoordinationV1LeaseSpec",
]
