# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.resource.v1beta1._async import AsyncResourceV1Beta1API
from httpx2_k8s.resource.v1beta1._sync import ResourceV1Beta1API

__all__ = ["AsyncResourceV1Beta1API", "ResourceV1Beta1API"]
