# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.resource.v1beta1._official_async import _OfficialResourceV1Beta1AsyncOperations


class AsyncResourceV1Beta1API(_OfficialResourceV1Beta1AsyncOperations):
    pass
