# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "SchedulingV1Alpha2API": "httpx2_k8s.scheduling.v1alpha2._sync",
    "AsyncSchedulingV1Alpha2API": "httpx2_k8s.scheduling.v1alpha2._async",
    "SchedulingV1Alpha2BasicSchedulingPolicy": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2GangSchedulingPolicy": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroup": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupList": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupResourceClaim": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupResourceClaimStatus": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupSchedulingConstraints": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupSchedulingPolicy": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupSpec": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupStatus": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupTemplate": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2PodGroupTemplateReference": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2TopologyConstraint": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2TypedLocalObjectReference": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2Workload": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2WorkloadList": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2WorkloadPodGroupTemplateReference": "httpx2_k8s.scheduling.v1alpha2._models",
    "SchedulingV1Alpha2WorkloadSpec": "httpx2_k8s.scheduling.v1alpha2._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncSchedulingV1Alpha2API",
    "SchedulingV1Alpha2API",
    "SchedulingV1Alpha2BasicSchedulingPolicy",
    "SchedulingV1Alpha2GangSchedulingPolicy",
    "SchedulingV1Alpha2PodGroup",
    "SchedulingV1Alpha2PodGroupList",
    "SchedulingV1Alpha2PodGroupResourceClaim",
    "SchedulingV1Alpha2PodGroupResourceClaimStatus",
    "SchedulingV1Alpha2PodGroupSchedulingConstraints",
    "SchedulingV1Alpha2PodGroupSchedulingPolicy",
    "SchedulingV1Alpha2PodGroupSpec",
    "SchedulingV1Alpha2PodGroupStatus",
    "SchedulingV1Alpha2PodGroupTemplate",
    "SchedulingV1Alpha2PodGroupTemplateReference",
    "SchedulingV1Alpha2TopologyConstraint",
    "SchedulingV1Alpha2TypedLocalObjectReference",
    "SchedulingV1Alpha2Workload",
    "SchedulingV1Alpha2WorkloadList",
    "SchedulingV1Alpha2WorkloadPodGroupTemplateReference",
    "SchedulingV1Alpha2WorkloadSpec",
]
