# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.scheduling.v1alpha2._official_async import (
    _OfficialSchedulingV1Alpha2AsyncOperations,
)


class AsyncSchedulingV1Alpha2API(_OfficialSchedulingV1Alpha2AsyncOperations):
    pass
