# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.authentication.v1._official_async import _OfficialAuthenticationV1AsyncOperations


class AsyncAuthenticationV1API(_OfficialAuthenticationV1AsyncOperations):
    pass
