# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.storagemigration.v1beta1._official_async import (
    _OfficialStorageMigrationV1Beta1AsyncOperations,
)


class AsyncStorageMigrationV1Beta1API(_OfficialStorageMigrationV1Beta1AsyncOperations):
    pass
