# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "CertificatesV1Beta1API": "httpx2_k8s.certificates.v1beta1._sync",
    "AsyncCertificatesV1Beta1API": "httpx2_k8s.certificates.v1beta1._async",
    "CertificatesV1Beta1ClusterTrustBundle": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1ClusterTrustBundleList": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1ClusterTrustBundleSpec": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1PodCertificateRequest": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1PodCertificateRequestList": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1PodCertificateRequestSpec": "httpx2_k8s.certificates.v1beta1._models",
    "CertificatesV1Beta1PodCertificateRequestStatus": "httpx2_k8s.certificates.v1beta1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncCertificatesV1Beta1API",
    "CertificatesV1Beta1API",
    "CertificatesV1Beta1ClusterTrustBundle",
    "CertificatesV1Beta1ClusterTrustBundleList",
    "CertificatesV1Beta1ClusterTrustBundleSpec",
    "CertificatesV1Beta1PodCertificateRequest",
    "CertificatesV1Beta1PodCertificateRequestList",
    "CertificatesV1Beta1PodCertificateRequestSpec",
    "CertificatesV1Beta1PodCertificateRequestStatus",
]
