# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.certificates.v1beta1._official_async import (
    _OfficialCertificatesV1Beta1AsyncOperations,
)


class AsyncCertificatesV1Beta1API(_OfficialCertificatesV1Beta1AsyncOperations):
    pass
