# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1Condition,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
    MetaV1Time,
)


class CertificatesV1Beta1ClusterTrustBundle(KubeModel):
    api_version: Literal["certificates.k8s.io/v1beta1"] = Field(
        default="certificates.k8s.io/v1beta1", alias="apiVersion"
    )
    kind: Literal["ClusterTrustBundle"] = Field(default="ClusterTrustBundle", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: CertificatesV1Beta1ClusterTrustBundleSpec = Field(
        default_factory=lambda: CertificatesV1Beta1ClusterTrustBundleSpec.model_construct(),
        alias="spec",
    )


class CertificatesV1Beta1ClusterTrustBundleList(KubeModel):
    api_version: Literal["certificates.k8s.io/v1beta1"] = Field(
        default="certificates.k8s.io/v1beta1", alias="apiVersion"
    )
    items: list[CertificatesV1Beta1ClusterTrustBundle] = Field(alias="items")
    kind: Literal["ClusterTrustBundleList"] = Field(default="ClusterTrustBundleList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class CertificatesV1Beta1ClusterTrustBundleSpec(KubeModel):
    signer_name: str | None = Field(default=None, alias="signerName")
    trust_bundle: str = Field(default="", alias="trustBundle")


class CertificatesV1Beta1PodCertificateRequest(KubeModel):
    api_version: Literal["certificates.k8s.io/v1beta1"] = Field(
        default="certificates.k8s.io/v1beta1", alias="apiVersion"
    )
    kind: Literal["PodCertificateRequest"] = Field(default="PodCertificateRequest", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: CertificatesV1Beta1PodCertificateRequestSpec = Field(
        default_factory=lambda: CertificatesV1Beta1PodCertificateRequestSpec.model_construct(),
        alias="spec",
    )
    status: CertificatesV1Beta1PodCertificateRequestStatus = Field(
        default_factory=lambda: CertificatesV1Beta1PodCertificateRequestStatus.model_construct(),
        alias="status",
    )


class CertificatesV1Beta1PodCertificateRequestList(KubeModel):
    api_version: Literal["certificates.k8s.io/v1beta1"] = Field(
        default="certificates.k8s.io/v1beta1", alias="apiVersion"
    )
    items: list[CertificatesV1Beta1PodCertificateRequest] = Field(alias="items")
    kind: Literal["PodCertificateRequestList"] = Field(
        default="PodCertificateRequestList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class CertificatesV1Beta1PodCertificateRequestSpec(KubeModel):
    max_expiration_seconds: int = Field(default=86400, alias="maxExpirationSeconds")
    node_name: str = Field(default="", alias="nodeName")
    node_uid: str = Field(default="", alias="nodeUID")
    pkix_public_key: Base64Data | None = Field(default=None, alias="pkixPublicKey")
    pod_name: str = Field(default="", alias="podName")
    pod_uid: str = Field(default="", alias="podUID")
    proof_of_possession: Base64Data | None = Field(default=None, alias="proofOfPossession")
    service_account_name: str = Field(default="", alias="serviceAccountName")
    service_account_uid: str = Field(default="", alias="serviceAccountUID")
    signer_name: str = Field(default="", alias="signerName")
    unverified_user_annotations: dict[str, str] | None = Field(
        default=None, alias="unverifiedUserAnnotations"
    )
    stub_pkcs10_request: Base64Data | None = Field(default=None, alias="stubPKCS10Request")


class CertificatesV1Beta1PodCertificateRequestStatus(KubeModel):
    begin_refresh_at: MetaV1Time | None = Field(default=None, alias="beginRefreshAt")
    certificate_chain: str | None = Field(default=None, alias="certificateChain")
    conditions: list[MetaV1Condition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )
    not_after: MetaV1Time | None = Field(default=None, alias="notAfter")
    not_before: MetaV1Time | None = Field(default=None, alias="notBefore")


__all__ = [
    "CertificatesV1Beta1ClusterTrustBundle",
    "CertificatesV1Beta1ClusterTrustBundleList",
    "CertificatesV1Beta1ClusterTrustBundleSpec",
    "CertificatesV1Beta1PodCertificateRequest",
    "CertificatesV1Beta1PodCertificateRequestList",
    "CertificatesV1Beta1PodCertificateRequestSpec",
    "CertificatesV1Beta1PodCertificateRequestStatus",
]
