# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "StorageMigrationV1Alpha1API": "httpx2_k8s.storagemigration.v1alpha1._sync",
    "AsyncStorageMigrationV1Alpha1API": "httpx2_k8s.storagemigration.v1alpha1._async",
    "StorageMigrationV1Alpha1GroupVersionResource": "httpx2_k8s.storagemigration.v1alpha1._models",
    "StorageMigrationV1Alpha1MigrationCondition": "httpx2_k8s.storagemigration.v1alpha1._models",
    "StorageMigrationV1Alpha1StorageVersionMigration": "httpx2_k8s.storagemigration.v1alpha1._models",
    "StorageMigrationV1Alpha1StorageVersionMigrationList": "httpx2_k8s.storagemigration.v1alpha1._models",
    "StorageMigrationV1Alpha1StorageVersionMigrationSpec": "httpx2_k8s.storagemigration.v1alpha1._models",
    "StorageMigrationV1Alpha1StorageVersionMigrationStatus": "httpx2_k8s.storagemigration.v1alpha1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncStorageMigrationV1Alpha1API",
    "StorageMigrationV1Alpha1API",
    "StorageMigrationV1Alpha1GroupVersionResource",
    "StorageMigrationV1Alpha1MigrationCondition",
    "StorageMigrationV1Alpha1StorageVersionMigration",
    "StorageMigrationV1Alpha1StorageVersionMigrationList",
    "StorageMigrationV1Alpha1StorageVersionMigrationSpec",
    "StorageMigrationV1Alpha1StorageVersionMigrationStatus",
]
