# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.certificates.v1._async import AsyncCertificatesV1API as _ExistingAsyncAPI
from httpx2_k8s.certificates.v1._official_async import _OfficialCertificatesV1AsyncOperations
from httpx2_k8s.certificates.v1._official_sync import _OfficialCertificatesV1SyncOperations
from httpx2_k8s.certificates.v1._sync import CertificatesV1API as _ExistingSyncAPI


class CertificatesV1API(_ExistingSyncAPI, _OfficialCertificatesV1SyncOperations):
    pass


class AsyncCertificatesV1API(_ExistingAsyncAPI, _OfficialCertificatesV1AsyncOperations):
    pass


__all__ = ["AsyncCertificatesV1API", "CertificatesV1API"]
