# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "AdmissionRegistrationV1Alpha1API": "httpx2_k8s.admissionregistration.v1alpha1._sync",
    "AsyncAdmissionRegistrationV1Alpha1API": "httpx2_k8s.admissionregistration.v1alpha1._async",
    "AdmissionRegistrationV1Alpha1ApplyConfiguration": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1AuditAnnotation": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ExpressionWarning": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1JSONPatch": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MatchCondition": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MatchResources": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicy": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBinding": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingList": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyList": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1Mutation": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1NamedRuleWithOperations": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ParamKind": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ParamRef": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1TypeChecking": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicy": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBinding": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingList": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyList": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1Validation": "httpx2_k8s.admissionregistration.v1alpha1._models",
    "AdmissionRegistrationV1Alpha1Variable": "httpx2_k8s.admissionregistration.v1alpha1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AdmissionRegistrationV1Alpha1API",
    "AdmissionRegistrationV1Alpha1ApplyConfiguration",
    "AdmissionRegistrationV1Alpha1AuditAnnotation",
    "AdmissionRegistrationV1Alpha1ExpressionWarning",
    "AdmissionRegistrationV1Alpha1JSONPatch",
    "AdmissionRegistrationV1Alpha1MatchCondition",
    "AdmissionRegistrationV1Alpha1MatchResources",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicy",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyList",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec",
    "AdmissionRegistrationV1Alpha1Mutation",
    "AdmissionRegistrationV1Alpha1NamedRuleWithOperations",
    "AdmissionRegistrationV1Alpha1ParamKind",
    "AdmissionRegistrationV1Alpha1ParamRef",
    "AdmissionRegistrationV1Alpha1TypeChecking",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicy",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyList",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus",
    "AdmissionRegistrationV1Alpha1Validation",
    "AdmissionRegistrationV1Alpha1Variable",
    "AsyncAdmissionRegistrationV1Alpha1API",
]
