# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1Condition,
    MetaV1LabelSelector,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
)


class AdmissionRegistrationV1Alpha1AuditAnnotation(KubeModel):
    key: str = Field(default="", alias="key")
    value_expression: str = Field(default="", alias="valueExpression")


class AdmissionRegistrationV1Alpha1ExpressionWarning(KubeModel):
    field_ref: str = Field(default="", alias="fieldRef")
    warning: str = Field(default="", alias="warning")


class AdmissionRegistrationV1Alpha1MatchCondition(KubeModel):
    expression: str = Field(default="", alias="expression")
    name: str = Field(default="", alias="name")


class AdmissionRegistrationV1Alpha1MatchResources(KubeModel):
    exclude_resource_rules: list[AdmissionRegistrationV1Alpha1NamedRuleWithOperations] | None = (
        Field(
            default=None,
            json_schema_extra={"x-kubernetes-list-type": "atomic"},
            alias="excludeResourceRules",
        )
    )
    match_policy: str | None = Field(default=None, alias="matchPolicy")
    namespace_selector: MetaV1LabelSelector | None = Field(default=None, alias="namespaceSelector")
    object_selector: MetaV1LabelSelector | None = Field(default=None, alias="objectSelector")
    resource_rules: list[AdmissionRegistrationV1Alpha1NamedRuleWithOperations] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceRules"
    )


class AdmissionRegistrationV1Alpha1NamedRuleWithOperations(KubeModel):
    api_groups: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiGroups"
    )
    api_versions: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="apiVersions"
    )
    operations: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="operations"
    )
    resource_names: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resourceNames"
    )
    resources: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="resources"
    )
    scope: str | None = Field(default=None, alias="scope")


class AdmissionRegistrationV1Alpha1ParamKind(KubeModel):
    api_version: str | None = Field(default=None, alias="apiVersion")
    kind: str | None = Field(default=None, alias="kind")


class AdmissionRegistrationV1Alpha1ParamRef(KubeModel):
    name: str | None = Field(default=None, alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    parameter_not_found_action: str | None = Field(default=None, alias="parameterNotFoundAction")
    selector: MetaV1LabelSelector | None = Field(default=None, alias="selector")


class AdmissionRegistrationV1Alpha1TypeChecking(KubeModel):
    expression_warnings: list[AdmissionRegistrationV1Alpha1ExpressionWarning] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="expressionWarnings",
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicy(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    kind: Literal["ValidatingAdmissionPolicy"] = Field(
        default="ValidatingAdmissionPolicy", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec.model_construct()
        ),
        alias="spec",
    )
    status: AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus.model_construct()
        ),
        alias="status",
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBinding(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    kind: Literal["ValidatingAdmissionPolicyBinding"] = Field(
        default="ValidatingAdmissionPolicyBinding", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBinding] = Field(
        alias="items"
    )
    kind: Literal["ValidatingAdmissionPolicyBindingList"] = Field(
        default="ValidatingAdmissionPolicyBindingList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec(KubeModel):
    match_resources: AdmissionRegistrationV1Alpha1MatchResources | None = Field(
        default=None, alias="matchResources"
    )
    param_ref: AdmissionRegistrationV1Alpha1ParamRef | None = Field(default=None, alias="paramRef")
    policy_name: str | None = Field(default=None, alias="policyName")
    validation_actions: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "set"}, alias="validationActions"
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicy] = Field(alias="items")
    kind: Literal["ValidatingAdmissionPolicyList"] = Field(
        default="ValidatingAdmissionPolicyList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec(KubeModel):
    audit_annotations: list[AdmissionRegistrationV1Alpha1AuditAnnotation] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="auditAnnotations",
    )
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1Alpha1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_constraints: AdmissionRegistrationV1Alpha1MatchResources | None = Field(
        default=None, alias="matchConstraints"
    )
    param_kind: AdmissionRegistrationV1Alpha1ParamKind | None = Field(
        default=None, alias="paramKind"
    )
    validations: list[AdmissionRegistrationV1Alpha1Validation] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="validations"
    )
    variables: list[AdmissionRegistrationV1Alpha1Variable] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="variables",
    )


class AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus(KubeModel):
    conditions: list[MetaV1Condition] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-map-keys": ["type"], "x-kubernetes-list-type": "map"},
        alias="conditions",
    )
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    type_checking: AdmissionRegistrationV1Alpha1TypeChecking | None = Field(
        default=None, alias="typeChecking"
    )


class AdmissionRegistrationV1Alpha1Validation(KubeModel):
    expression: str = Field(default="", alias="expression")
    message: str | None = Field(default=None, alias="message")
    message_expression: str | None = Field(default=None, alias="messageExpression")
    reason: str | None = Field(default=None, alias="reason")


class AdmissionRegistrationV1Alpha1Variable(KubeModel):
    expression: str = Field(default="", alias="expression")
    name: str = Field(default="", alias="name")


class AdmissionRegistrationV1Alpha1ApplyConfiguration(KubeModel):
    expression: str | None = Field(default=None, alias="expression")


class AdmissionRegistrationV1Alpha1JSONPatch(KubeModel):
    expression: str | None = Field(default=None, alias="expression")


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicy(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    kind: Literal["MutatingAdmissionPolicy"] = Field(
        default="MutatingAdmissionPolicy", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBinding(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    kind: Literal["MutatingAdmissionPolicyBinding"] = Field(
        default="MutatingAdmissionPolicyBinding", alias="kind"
    )
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec = Field(
        default_factory=lambda: (
            AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec.model_construct()
        ),
        alias="spec",
    )


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBinding] = Field(alias="items")
    kind: Literal["MutatingAdmissionPolicyBindingList"] = Field(
        default="MutatingAdmissionPolicyBindingList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec(KubeModel):
    match_resources: AdmissionRegistrationV1Alpha1MatchResources | None = Field(
        default=None, alias="matchResources"
    )
    param_ref: AdmissionRegistrationV1Alpha1ParamRef | None = Field(default=None, alias="paramRef")
    policy_name: str | None = Field(default=None, alias="policyName")


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyList(KubeModel):
    api_version: Literal["admissionregistration.k8s.io/v1alpha1"] = Field(
        default="admissionregistration.k8s.io/v1alpha1", alias="apiVersion"
    )
    items: list[AdmissionRegistrationV1Alpha1MutatingAdmissionPolicy] = Field(alias="items")
    kind: Literal["MutatingAdmissionPolicyList"] = Field(
        default="MutatingAdmissionPolicyList", alias="kind"
    )
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec(KubeModel):
    failure_policy: str | None = Field(default=None, alias="failurePolicy")
    match_conditions: list[AdmissionRegistrationV1Alpha1MatchCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["name"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "name",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="matchConditions",
    )
    match_constraints: AdmissionRegistrationV1Alpha1MatchResources | None = Field(
        default=None, alias="matchConstraints"
    )
    mutations: list[AdmissionRegistrationV1Alpha1Mutation] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="mutations"
    )
    param_kind: AdmissionRegistrationV1Alpha1ParamKind | None = Field(
        default=None, alias="paramKind"
    )
    reinvocation_policy: str | None = Field(default=None, alias="reinvocationPolicy")
    variables: list[AdmissionRegistrationV1Alpha1Variable] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="variables"
    )


class AdmissionRegistrationV1Alpha1Mutation(KubeModel):
    apply_configuration: AdmissionRegistrationV1Alpha1ApplyConfiguration | None = Field(
        default=None, alias="applyConfiguration"
    )
    json_patch: AdmissionRegistrationV1Alpha1JSONPatch | None = Field(
        default=None, alias="jsonPatch"
    )
    patch_type: str = Field(default="", alias="patchType")


__all__ = [
    "AdmissionRegistrationV1Alpha1AuditAnnotation",
    "AdmissionRegistrationV1Alpha1ExpressionWarning",
    "AdmissionRegistrationV1Alpha1MatchCondition",
    "AdmissionRegistrationV1Alpha1MatchResources",
    "AdmissionRegistrationV1Alpha1NamedRuleWithOperations",
    "AdmissionRegistrationV1Alpha1ParamKind",
    "AdmissionRegistrationV1Alpha1ParamRef",
    "AdmissionRegistrationV1Alpha1TypeChecking",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicy",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyList",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicySpec",
    "AdmissionRegistrationV1Alpha1ValidatingAdmissionPolicyStatus",
    "AdmissionRegistrationV1Alpha1Validation",
    "AdmissionRegistrationV1Alpha1Variable",
    "AdmissionRegistrationV1Alpha1ApplyConfiguration",
    "AdmissionRegistrationV1Alpha1JSONPatch",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicy",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBinding",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingList",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyBindingSpec",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicyList",
    "AdmissionRegistrationV1Alpha1MutatingAdmissionPolicySpec",
    "AdmissionRegistrationV1Alpha1Mutation",
]
