# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.admissionregistration.v1alpha1._official_sync import (
    _OfficialAdmissionRegistrationV1Alpha1SyncOperations,
)


class AdmissionRegistrationV1Alpha1API(_OfficialAdmissionRegistrationV1Alpha1SyncOperations):
    pass
