# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    MetaV1ObjectMeta,
)
from httpx2_k8s.authentication.v1._models import (
    AuthenticationV1UserInfo,
)


class AuthenticationV1Alpha1SelfSubjectReview(KubeModel):
    api_version: Literal["authentication.k8s.io/v1alpha1"] = Field(
        default="authentication.k8s.io/v1alpha1", alias="apiVersion"
    )
    kind: Literal["SelfSubjectReview"] = Field(default="SelfSubjectReview", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    status: AuthenticationV1Alpha1SelfSubjectReviewStatus = Field(
        default_factory=lambda: AuthenticationV1Alpha1SelfSubjectReviewStatus.model_construct(),
        alias="status",
    )


class AuthenticationV1Alpha1SelfSubjectReviewStatus(KubeModel):
    user_info: AuthenticationV1UserInfo = Field(
        default_factory=lambda: AuthenticationV1UserInfo.model_construct(), alias="userInfo"
    )


__all__ = [
    "AuthenticationV1Alpha1SelfSubjectReview",
    "AuthenticationV1Alpha1SelfSubjectReviewStatus",
]
