# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Iterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_watch_response, query_parameters
from httpx2_k8s._protocols import SyncKubeClientProtocol
from httpx2_k8s.models import (
    AuthenticationV1Alpha1SelfSubjectReview,
    MetaV1APIResourceList,
)


class _OfficialAuthenticationV1Alpha1SyncOperations:
    _client: SyncKubeClientProtocol

    def __init__(self, client: SyncKubeClientProtocol) -> None:
        self._client = client

    def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/authentication.k8s.io/v1alpha1/"
        params = {}
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    def create_self_subject_review(
        self,
        body: AuthenticationV1Alpha1SelfSubjectReview,
        *,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        pretty: str | None = None,
    ) -> AuthenticationV1Alpha1SelfSubjectReview:
        _path = "/apis/authentication.k8s.io/v1alpha1/selfsubjectreviews"
        params = query_parameters(
            {
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "pretty": pretty,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AuthenticationV1Alpha1SelfSubjectReview,
            params=params,
            body=body,
        )
