# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import AsyncIterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_async_watch_response, query_parameters
from httpx2_k8s._protocols import AsyncKubeClientProtocol
from httpx2_k8s.models import (
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
    ResourceV1DeviceClass,
    ResourceV1DeviceClassList,
    ResourceV1ResourceClaim,
    ResourceV1ResourceClaimList,
    ResourceV1ResourceClaimTemplate,
    ResourceV1ResourceClaimTemplateList,
    ResourceV1ResourceSlice,
    ResourceV1ResourceSliceList,
)


class _OfficialResourceV1AsyncOperations:
    _client: AsyncKubeClientProtocol

    def __init__(self, client: AsyncKubeClientProtocol) -> None:
        self._client = client

    async def delete_collection_device_class(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/resource.k8s.io/v1/deviceclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_device_class(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> ResourceV1DeviceClass:
        _path = f"/apis/resource.k8s.io/v1/deviceclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=ResourceV1DeviceClass,
            params=params,
            body=body,
        )

    async def delete_collection_namespaced_resource_claim(
        self,
        namespace: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_namespaced_resource_claim(
        self,
        namespace: str,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
        )

    async def delete_collection_namespaced_resource_claim_template(
        self,
        namespace: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = (
            f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_namespaced_resource_claim_template(
        self,
        namespace: str,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> ResourceV1ResourceClaimTemplate:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=ResourceV1ResourceClaimTemplate,
            params=params,
            body=body,
        )

    async def delete_collection_resource_slice(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/resource.k8s.io/v1/resourceslices"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_resource_slice(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> ResourceV1ResourceSlice:
        _path = f"/apis/resource.k8s.io/v1/resourceslices/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=ResourceV1ResourceSlice,
            params=params,
            body=body,
        )

    async def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/resource.k8s.io/v1/"
        params = {}
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    async def list_device_class(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1DeviceClassList:
        _path = "/apis/resource.k8s.io/v1/deviceclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1DeviceClassList,
            params=params,
        )

    async def read_device_class(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> ResourceV1DeviceClass:
        _path = f"/apis/resource.k8s.io/v1/deviceclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1DeviceClass,
            params=params,
        )

    async def list_namespaced_resource_claim(
        self,
        namespace: str,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1ResourceClaimList:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaimList,
            params=params,
        )

    async def read_namespaced_resource_claim(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
        )

    async def read_namespaced_resource_claim_status(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
        )

    async def list_namespaced_resource_claim_template(
        self,
        namespace: str,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1ResourceClaimTemplateList:
        _path = (
            f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaimTemplateList,
            params=params,
        )

    async def read_namespaced_resource_claim_template(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> ResourceV1ResourceClaimTemplate:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaimTemplate,
            params=params,
        )

    async def list_resource_claim_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1ResourceClaimList:
        _path = "/apis/resource.k8s.io/v1/resourceclaims"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaimList,
            params=params,
        )

    async def list_resource_claim_template_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1ResourceClaimTemplateList:
        _path = "/apis/resource.k8s.io/v1/resourceclaimtemplates"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceClaimTemplateList,
            params=params,
        )

    async def list_resource_slice(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> ResourceV1ResourceSliceList:
        _path = "/apis/resource.k8s.io/v1/resourceslices"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceSliceList,
            params=params,
        )

    async def read_resource_slice(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> ResourceV1ResourceSlice:
        _path = f"/apis/resource.k8s.io/v1/resourceslices/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=ResourceV1ResourceSlice,
            params=params,
        )

    async def watch_device_class_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/resource.k8s.io/v1/watch/deviceclasses"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_device_class(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/resource.k8s.io/v1/watch/deviceclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_namespaced_resource_claim_list(
        self,
        namespace: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = (
            f"/apis/resource.k8s.io/v1/watch/namespaces/{resource_name(namespace)}/resourceclaims"
        )
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_namespaced_resource_claim(
        self,
        namespace: str,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/resource.k8s.io/v1/watch/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_namespaced_resource_claim_template_list(
        self,
        namespace: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = f"/apis/resource.k8s.io/v1/watch/namespaces/{resource_name(namespace)}/resourceclaimtemplates"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_namespaced_resource_claim_template(
        self,
        namespace: str,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/resource.k8s.io/v1/watch/namespaces/{resource_name(namespace)}/resourceclaimtemplates/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_resource_claim_list_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/resource.k8s.io/v1/watch/resourceclaims"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_resource_claim_template_list_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/resource.k8s.io/v1/watch/resourceclaimtemplates"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_resource_slice_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/resource.k8s.io/v1/watch/resourceslices"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_resource_slice(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/resource.k8s.io/v1/watch/resourceslices/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def patch_device_class(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> ResourceV1DeviceClass:
        _path = f"/apis/resource.k8s.io/v1/deviceclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=ResourceV1DeviceClass,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_namespaced_resource_claim(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_namespaced_resource_claim_status(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_namespaced_resource_claim_template(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> ResourceV1ResourceClaimTemplate:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=ResourceV1ResourceClaimTemplate,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_resource_slice(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> ResourceV1ResourceSlice:
        _path = f"/apis/resource.k8s.io/v1/resourceslices/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=ResourceV1ResourceSlice,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def create_device_class(
        self,
        body: ResourceV1DeviceClass,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1DeviceClass:
        _path = "/apis/resource.k8s.io/v1/deviceclasses"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=ResourceV1DeviceClass,
            params=params,
            body=body,
        )

    async def create_namespaced_resource_claim(
        self,
        namespace: str,
        body: ResourceV1ResourceClaim,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
        )

    async def create_namespaced_resource_claim_template(
        self,
        namespace: str,
        body: ResourceV1ResourceClaimTemplate,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceClaimTemplate:
        _path = (
            f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=ResourceV1ResourceClaimTemplate,
            params=params,
            body=body,
        )

    async def create_resource_slice(
        self,
        body: ResourceV1ResourceSlice,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceSlice:
        _path = "/apis/resource.k8s.io/v1/resourceslices"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=ResourceV1ResourceSlice,
            params=params,
            body=body,
        )

    async def replace_device_class(
        self,
        name: str,
        body: ResourceV1DeviceClass,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1DeviceClass:
        _path = f"/apis/resource.k8s.io/v1/deviceclasses/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=ResourceV1DeviceClass,
            params=params,
            body=body,
        )

    async def replace_namespaced_resource_claim(
        self,
        namespace: str,
        name: str,
        body: ResourceV1ResourceClaim,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
        )

    async def replace_namespaced_resource_claim_status(
        self,
        namespace: str,
        name: str,
        body: ResourceV1ResourceClaim,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceClaim:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaims/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=ResourceV1ResourceClaim,
            params=params,
            body=body,
        )

    async def replace_namespaced_resource_claim_template(
        self,
        namespace: str,
        name: str,
        body: ResourceV1ResourceClaimTemplate,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceClaimTemplate:
        _path = f"/apis/resource.k8s.io/v1/namespaces/{resource_name(namespace)}/resourceclaimtemplates/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=ResourceV1ResourceClaimTemplate,
            params=params,
            body=body,
        )

    async def replace_resource_slice(
        self,
        name: str,
        body: ResourceV1ResourceSlice,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> ResourceV1ResourceSlice:
        _path = f"/apis/resource.k8s.io/v1/resourceslices/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=ResourceV1ResourceSlice,
            params=params,
            body=body,
        )
