# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    IntOrString,
    MetaV1LabelSelector,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
    MetaV1Time,
    RuntimeRawExtension,
)
from httpx2_k8s.core.v1._models import (
    CoreV1PersistentVolumeClaim,
    CoreV1PodTemplateSpec,
)


class AppsV1ControllerRevision(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    data: RuntimeRawExtension | None = Field(default=None, alias="data")
    kind: Literal["ControllerRevision"] = Field(default="ControllerRevision", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    revision: int = Field(default=0, alias="revision")


class AppsV1ControllerRevisionList(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    items: list[AppsV1ControllerRevision] = Field(alias="items")
    kind: Literal["ControllerRevisionList"] = Field(default="ControllerRevisionList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AppsV1DaemonSet(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    kind: Literal["DaemonSet"] = Field(default="DaemonSet", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AppsV1DaemonSetSpec = Field(
        default_factory=lambda: AppsV1DaemonSetSpec.model_construct(), alias="spec"
    )
    status: AppsV1DaemonSetStatus = Field(
        default_factory=lambda: AppsV1DaemonSetStatus.model_construct(), alias="status"
    )


class AppsV1DaemonSetCondition(KubeModel):
    last_transition_time: MetaV1Time | None = Field(default=None, alias="lastTransitionTime")
    message: str | None = Field(default=None, alias="message")
    reason: str | None = Field(default=None, alias="reason")
    status: str = Field(default="", alias="status")
    type_: str = Field(default="", alias="type")


class AppsV1DaemonSetList(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    items: list[AppsV1DaemonSet] = Field(alias="items")
    kind: Literal["DaemonSetList"] = Field(default="DaemonSetList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AppsV1DaemonSetSpec(KubeModel):
    min_ready_seconds: int | None = Field(default=None, alias="minReadySeconds")
    revision_history_limit: int | None = Field(default=None, alias="revisionHistoryLimit")
    selector: MetaV1LabelSelector = Field(alias="selector")
    template: CoreV1PodTemplateSpec = Field(
        default_factory=lambda: CoreV1PodTemplateSpec.model_construct(), alias="template"
    )
    update_strategy: AppsV1DaemonSetUpdateStrategy = Field(
        default_factory=lambda: AppsV1DaemonSetUpdateStrategy.model_construct(),
        alias="updateStrategy",
    )


class AppsV1DaemonSetStatus(KubeModel):
    collision_count: int | None = Field(default=None, alias="collisionCount")
    conditions: list[AppsV1DaemonSetCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )
    current_number_scheduled: int = Field(default=0, alias="currentNumberScheduled")
    desired_number_scheduled: int = Field(default=0, alias="desiredNumberScheduled")
    number_available: int | None = Field(default=None, alias="numberAvailable")
    number_misscheduled: int = Field(default=0, alias="numberMisscheduled")
    number_ready: int = Field(default=0, alias="numberReady")
    number_unavailable: int | None = Field(default=None, alias="numberUnavailable")
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    updated_number_scheduled: int | None = Field(default=None, alias="updatedNumberScheduled")


class AppsV1DaemonSetUpdateStrategy(KubeModel):
    rolling_update: AppsV1RollingUpdateDaemonSet | None = Field(default=None, alias="rollingUpdate")
    type_: str | None = Field(default=None, alias="type")


class AppsV1Deployment(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    kind: Literal["Deployment"] = Field(default="Deployment", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AppsV1DeploymentSpec = Field(
        default_factory=lambda: AppsV1DeploymentSpec.model_construct(), alias="spec"
    )
    status: AppsV1DeploymentStatus = Field(
        default_factory=lambda: AppsV1DeploymentStatus.model_construct(), alias="status"
    )


class AppsV1DeploymentCondition(KubeModel):
    last_transition_time: MetaV1Time | None = Field(default=None, alias="lastTransitionTime")
    last_update_time: MetaV1Time | None = Field(default=None, alias="lastUpdateTime")
    message: str | None = Field(default=None, alias="message")
    reason: str | None = Field(default=None, alias="reason")
    status: str = Field(default="", alias="status")
    type_: str = Field(default="", alias="type")


class AppsV1DeploymentList(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    items: list[AppsV1Deployment] = Field(alias="items")
    kind: Literal["DeploymentList"] = Field(default="DeploymentList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AppsV1DeploymentSpec(KubeModel):
    min_ready_seconds: int | None = Field(default=None, alias="minReadySeconds")
    paused: bool | None = Field(default=None, alias="paused")
    progress_deadline_seconds: int | None = Field(default=None, alias="progressDeadlineSeconds")
    replicas: int | None = Field(default=None, alias="replicas")
    revision_history_limit: int | None = Field(default=None, alias="revisionHistoryLimit")
    selector: MetaV1LabelSelector = Field(alias="selector")
    strategy: AppsV1DeploymentStrategy = Field(
        default_factory=lambda: AppsV1DeploymentStrategy.model_construct(),
        json_schema_extra={"x-kubernetes-patch-strategy": "retainKeys"},
        alias="strategy",
    )
    template: CoreV1PodTemplateSpec = Field(
        default_factory=lambda: CoreV1PodTemplateSpec.model_construct(), alias="template"
    )


class AppsV1DeploymentStatus(KubeModel):
    available_replicas: int | None = Field(default=None, alias="availableReplicas")
    collision_count: int | None = Field(default=None, alias="collisionCount")
    conditions: list[AppsV1DeploymentCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    ready_replicas: int | None = Field(default=None, alias="readyReplicas")
    replicas: int | None = Field(default=None, alias="replicas")
    unavailable_replicas: int | None = Field(default=None, alias="unavailableReplicas")
    updated_replicas: int | None = Field(default=None, alias="updatedReplicas")
    terminating_replicas: int | None = Field(default=None, alias="terminatingReplicas")


class AppsV1DeploymentStrategy(KubeModel):
    rolling_update: AppsV1RollingUpdateDeployment | None = Field(
        default=None, alias="rollingUpdate"
    )
    type_: str | None = Field(default=None, alias="type")


class AppsV1ReplicaSet(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    kind: Literal["ReplicaSet"] = Field(default="ReplicaSet", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AppsV1ReplicaSetSpec = Field(
        default_factory=lambda: AppsV1ReplicaSetSpec.model_construct(), alias="spec"
    )
    status: AppsV1ReplicaSetStatus = Field(
        default_factory=lambda: AppsV1ReplicaSetStatus.model_construct(), alias="status"
    )


class AppsV1ReplicaSetCondition(KubeModel):
    last_transition_time: MetaV1Time | None = Field(default=None, alias="lastTransitionTime")
    message: str | None = Field(default=None, alias="message")
    reason: str | None = Field(default=None, alias="reason")
    status: str = Field(default="", alias="status")
    type_: str = Field(default="", alias="type")


class AppsV1ReplicaSetList(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    items: list[AppsV1ReplicaSet] = Field(alias="items")
    kind: Literal["ReplicaSetList"] = Field(default="ReplicaSetList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AppsV1ReplicaSetSpec(KubeModel):
    min_ready_seconds: int | None = Field(default=None, alias="minReadySeconds")
    replicas: int | None = Field(default=None, alias="replicas")
    selector: MetaV1LabelSelector = Field(alias="selector")
    template: CoreV1PodTemplateSpec = Field(
        default_factory=lambda: CoreV1PodTemplateSpec.model_construct(), alias="template"
    )


class AppsV1ReplicaSetStatus(KubeModel):
    available_replicas: int | None = Field(default=None, alias="availableReplicas")
    conditions: list[AppsV1ReplicaSetCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )
    fully_labeled_replicas: int | None = Field(default=None, alias="fullyLabeledReplicas")
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    ready_replicas: int | None = Field(default=None, alias="readyReplicas")
    replicas: int = Field(default=0, alias="replicas")
    terminating_replicas: int | None = Field(default=None, alias="terminatingReplicas")


class AppsV1RollingUpdateDaemonSet(KubeModel):
    max_surge: IntOrString | None = Field(default=None, alias="maxSurge")
    max_unavailable: IntOrString | None = Field(default=None, alias="maxUnavailable")


class AppsV1RollingUpdateDeployment(KubeModel):
    max_surge: IntOrString | None = Field(default=None, alias="maxSurge")
    max_unavailable: IntOrString | None = Field(default=None, alias="maxUnavailable")


class AppsV1RollingUpdateStatefulSetStrategy(KubeModel):
    max_unavailable: IntOrString | None = Field(default=None, alias="maxUnavailable")
    partition: int | None = Field(default=None, alias="partition")


class AppsV1StatefulSet(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    kind: Literal["StatefulSet"] = Field(default="StatefulSet", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: AppsV1StatefulSetSpec = Field(
        default_factory=lambda: AppsV1StatefulSetSpec.model_construct(), alias="spec"
    )
    status: AppsV1StatefulSetStatus = Field(
        default_factory=lambda: AppsV1StatefulSetStatus.model_construct(), alias="status"
    )


class AppsV1StatefulSetCondition(KubeModel):
    last_transition_time: MetaV1Time | None = Field(default=None, alias="lastTransitionTime")
    message: str | None = Field(default=None, alias="message")
    reason: str | None = Field(default=None, alias="reason")
    status: str = Field(default="", alias="status")
    type_: str = Field(default="", alias="type")


class AppsV1StatefulSetList(KubeModel):
    api_version: Literal["apps/v1"] = Field(default="apps/v1", alias="apiVersion")
    items: list[AppsV1StatefulSet] = Field(alias="items")
    kind: Literal["StatefulSetList"] = Field(default="StatefulSetList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class AppsV1StatefulSetOrdinals(KubeModel):
    start: int = Field(default=0, alias="start")


class AppsV1StatefulSetPersistentVolumeClaimRetentionPolicy(KubeModel):
    when_deleted: str | None = Field(default=None, alias="whenDeleted")
    when_scaled: str | None = Field(default=None, alias="whenScaled")


class AppsV1StatefulSetSpec(KubeModel):
    min_ready_seconds: int | None = Field(default=None, alias="minReadySeconds")
    ordinals: AppsV1StatefulSetOrdinals | None = Field(default=None, alias="ordinals")
    persistent_volume_claim_retention_policy: (
        AppsV1StatefulSetPersistentVolumeClaimRetentionPolicy | None
    ) = Field(default=None, alias="persistentVolumeClaimRetentionPolicy")
    pod_management_policy: str | None = Field(default=None, alias="podManagementPolicy")
    replicas: int | None = Field(default=None, alias="replicas")
    revision_history_limit: int | None = Field(default=None, alias="revisionHistoryLimit")
    selector: MetaV1LabelSelector = Field(alias="selector")
    service_name: str = Field(default="", alias="serviceName")
    template: CoreV1PodTemplateSpec = Field(
        default_factory=lambda: CoreV1PodTemplateSpec.model_construct(), alias="template"
    )
    update_strategy: AppsV1StatefulSetUpdateStrategy = Field(
        default_factory=lambda: AppsV1StatefulSetUpdateStrategy.model_construct(),
        alias="updateStrategy",
    )
    volume_claim_templates: list[CoreV1PersistentVolumeClaim] | None = Field(
        default=None,
        json_schema_extra={"x-kubernetes-list-type": "atomic"},
        alias="volumeClaimTemplates",
    )


class AppsV1StatefulSetStatus(KubeModel):
    available_replicas: int = Field(default=0, alias="availableReplicas")
    collision_count: int | None = Field(default=None, alias="collisionCount")
    conditions: list[AppsV1StatefulSetCondition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )
    current_replicas: int | None = Field(default=None, alias="currentReplicas")
    current_revision: str | None = Field(default=None, alias="currentRevision")
    observed_generation: int | None = Field(default=None, alias="observedGeneration")
    ready_replicas: int | None = Field(default=None, alias="readyReplicas")
    replicas: int = Field(default=0, alias="replicas")
    update_revision: str | None = Field(default=None, alias="updateRevision")
    updated_replicas: int | None = Field(default=None, alias="updatedReplicas")


class AppsV1StatefulSetUpdateStrategy(KubeModel):
    rolling_update: AppsV1RollingUpdateStatefulSetStrategy | None = Field(
        default=None, alias="rollingUpdate"
    )
    type_: str | None = Field(default=None, alias="type")


__all__ = [
    "AppsV1ControllerRevision",
    "AppsV1ControllerRevisionList",
    "AppsV1DaemonSet",
    "AppsV1DaemonSetCondition",
    "AppsV1DaemonSetList",
    "AppsV1DaemonSetSpec",
    "AppsV1DaemonSetStatus",
    "AppsV1DaemonSetUpdateStrategy",
    "AppsV1Deployment",
    "AppsV1DeploymentCondition",
    "AppsV1DeploymentList",
    "AppsV1DeploymentSpec",
    "AppsV1DeploymentStatus",
    "AppsV1DeploymentStrategy",
    "AppsV1ReplicaSet",
    "AppsV1ReplicaSetCondition",
    "AppsV1ReplicaSetList",
    "AppsV1ReplicaSetSpec",
    "AppsV1ReplicaSetStatus",
    "AppsV1RollingUpdateDaemonSet",
    "AppsV1RollingUpdateDeployment",
    "AppsV1RollingUpdateStatefulSetStrategy",
    "AppsV1StatefulSet",
    "AppsV1StatefulSetCondition",
    "AppsV1StatefulSetList",
    "AppsV1StatefulSetOrdinals",
    "AppsV1StatefulSetPersistentVolumeClaimRetentionPolicy",
    "AppsV1StatefulSetSpec",
    "AppsV1StatefulSetStatus",
    "AppsV1StatefulSetUpdateStrategy",
]
