# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.flowcontrol.v1beta3._official_async import (
    _OfficialFlowControlV1Beta3AsyncOperations,
)


class AsyncFlowControlV1Beta3API(_OfficialFlowControlV1Beta3AsyncOperations):
    pass
