# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import AsyncIterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_async_watch_response, query_parameters
from httpx2_k8s._protocols import AsyncKubeClientProtocol
from httpx2_k8s.models import (
    FlowControlV1Beta3FlowSchema,
    FlowControlV1Beta3FlowSchemaList,
    FlowControlV1Beta3PriorityLevelConfiguration,
    FlowControlV1Beta3PriorityLevelConfigurationList,
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
)


class _OfficialFlowControlV1Beta3AsyncOperations:
    _client: AsyncKubeClientProtocol

    def __init__(self, client: AsyncKubeClientProtocol) -> None:
        self._client = client

    async def delete_collection_flow_schema(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_flow_schema(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_collection_priority_level_configuration(
        self,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def delete_priority_level_configuration(
        self,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return await self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    async def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/"
        params = {}
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    async def list_flow_schema(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> FlowControlV1Beta3FlowSchemaList:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3FlowSchemaList,
            params=params,
        )

    async def read_flow_schema(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> FlowControlV1Beta3FlowSchema:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
        )

    async def read_flow_schema_status(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> FlowControlV1Beta3FlowSchema:
        _path = (
            f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}/status"
        )
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
        )

    async def list_priority_level_configuration(
        self,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfigurationList:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfigurationList,
            params=params,
        )

    async def read_priority_level_configuration(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
        )

    async def read_priority_level_configuration_status(
        self,
        name: str,
        *,
        pretty: str | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
        )

    async def watch_flow_schema_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/watch/flowschemas"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_flow_schema(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = (
            f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/watch/flowschemas/{resource_name(name)}"
        )
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def watch_priority_level_configuration_list(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/watch/prioritylevelconfigurations"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return await self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_priority_level_configuration(
        self,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AsyncIterator[MetaV1WatchEvent]:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/watch/prioritylevelconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_async_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    async def patch_flow_schema(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> FlowControlV1Beta3FlowSchema:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_flow_schema_status(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> FlowControlV1Beta3FlowSchema:
        _path = (
            f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}/status"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_priority_level_configuration(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def patch_priority_level_configuration_status(
        self,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return await self._client.request(
            "PATCH",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
            body=body,
            content_type=content_type,
        )

    async def create_flow_schema(
        self,
        body: FlowControlV1Beta3FlowSchema,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3FlowSchema:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
            body=body,
        )

    async def create_priority_level_configuration(
        self,
        body: FlowControlV1Beta3PriorityLevelConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = "/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "POST",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
            body=body,
        )

    async def replace_flow_schema(
        self,
        name: str,
        body: FlowControlV1Beta3FlowSchema,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3FlowSchema:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
            body=body,
        )

    async def replace_flow_schema_status(
        self,
        name: str,
        body: FlowControlV1Beta3FlowSchema,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3FlowSchema:
        _path = (
            f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/flowschemas/{resource_name(name)}/status"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=FlowControlV1Beta3FlowSchema,
            params=params,
            body=body,
        )

    async def replace_priority_level_configuration(
        self,
        name: str,
        body: FlowControlV1Beta3PriorityLevelConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
            body=body,
        )

    async def replace_priority_level_configuration_status(
        self,
        name: str,
        body: FlowControlV1Beta3PriorityLevelConfiguration,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> FlowControlV1Beta3PriorityLevelConfiguration:
        _path = f"/apis/flowcontrol.apiserver.k8s.io/v1beta3/prioritylevelconfigurations/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return await self._client.request(
            "PUT",
            _path,
            response_model=FlowControlV1Beta3PriorityLevelConfiguration,
            params=params,
            body=body,
        )
