# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.networking.v1._async import AsyncNetworkingV1API as _ExistingAsyncAPI
from httpx2_k8s.networking.v1._official_async import _OfficialNetworkingV1AsyncOperations
from httpx2_k8s.networking.v1._official_sync import _OfficialNetworkingV1SyncOperations
from httpx2_k8s.networking.v1._sync import NetworkingV1API as _ExistingSyncAPI


class NetworkingV1API(_ExistingSyncAPI, _OfficialNetworkingV1SyncOperations):
    pass


class AsyncNetworkingV1API(_ExistingAsyncAPI, _OfficialNetworkingV1AsyncOperations):
    pass
