# Generated by scripts/generate_official_models.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from datetime import datetime
from typing import Literal, TypeAlias

from pydantic import Field, JsonValue

from httpx2_k8s._models import Base64Data, KubeModel
from httpx2_k8s.apimachinery import (
    IntOrString,
    MetaV1Condition,
    MetaV1LabelSelector,
    MetaV1ListMeta,
    MetaV1ObjectMeta,
)
from httpx2_k8s.core.v1._models import (
    CoreV1TypedLocalObjectReference,
)


class NetworkingV1HTTPIngressPath(KubeModel):
    backend: NetworkingV1IngressBackend = Field(
        default_factory=lambda: NetworkingV1IngressBackend.model_construct(), alias="backend"
    )
    path: str | None = Field(default=None, alias="path")
    path_type: str = Field(alias="pathType")


class NetworkingV1HTTPIngressRuleValue(KubeModel):
    paths: list[NetworkingV1HTTPIngressPath] = Field(
        json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="paths"
    )


class NetworkingV1IPBlock(KubeModel):
    cidr: str = Field(default="", alias="cidr")
    except_: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="except"
    )


class NetworkingV1Ingress(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["Ingress"] = Field(default="Ingress", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1IngressSpec = Field(
        default_factory=lambda: NetworkingV1IngressSpec.model_construct(), alias="spec"
    )
    status: NetworkingV1IngressStatus = Field(
        default_factory=lambda: NetworkingV1IngressStatus.model_construct(), alias="status"
    )


class NetworkingV1IngressBackend(KubeModel):
    resource: CoreV1TypedLocalObjectReference | None = Field(default=None, alias="resource")
    service: NetworkingV1IngressServiceBackend | None = Field(default=None, alias="service")


class NetworkingV1IngressClass(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["IngressClass"] = Field(default="IngressClass", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1IngressClassSpec = Field(
        default_factory=lambda: NetworkingV1IngressClassSpec.model_construct(), alias="spec"
    )


class NetworkingV1IngressClassList(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    items: list[NetworkingV1IngressClass] = Field(alias="items")
    kind: Literal["IngressClassList"] = Field(default="IngressClassList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1IngressClassParametersReference(KubeModel):
    api_group: str | None = Field(default=None, alias="apiGroup")
    kind: str = Field(default="", alias="kind")
    name: str = Field(default="", alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    scope: str | None = Field(default=None, alias="scope")


class NetworkingV1IngressClassSpec(KubeModel):
    controller: str | None = Field(default=None, alias="controller")
    parameters: NetworkingV1IngressClassParametersReference | None = Field(
        default=None, alias="parameters"
    )


class NetworkingV1IngressList(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    items: list[NetworkingV1Ingress] = Field(alias="items")
    kind: Literal["IngressList"] = Field(default="IngressList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1IngressLoadBalancerIngress(KubeModel):
    hostname: str | None = Field(default=None, alias="hostname")
    ip: str | None = Field(default=None, alias="ip")
    ports: list[NetworkingV1IngressPortStatus] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="ports"
    )


class NetworkingV1IngressLoadBalancerStatus(KubeModel):
    ingress: list[NetworkingV1IngressLoadBalancerIngress] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="ingress"
    )


class NetworkingV1IngressPortStatus(KubeModel):
    error: str | None = Field(default=None, alias="error")
    port: int = Field(default=0, alias="port")
    protocol: str = Field(default="", alias="protocol")


class NetworkingV1IngressRule(KubeModel):
    host: str | None = Field(default=None, alias="host")
    http: NetworkingV1HTTPIngressRuleValue | None = Field(default=None, alias="http")


class NetworkingV1IngressServiceBackend(KubeModel):
    name: str = Field(default="", alias="name")
    port: NetworkingV1ServiceBackendPort = Field(
        default_factory=lambda: NetworkingV1ServiceBackendPort.model_construct(), alias="port"
    )


class NetworkingV1IngressSpec(KubeModel):
    default_backend: NetworkingV1IngressBackend | None = Field(default=None, alias="defaultBackend")
    ingress_class_name: str | None = Field(default=None, alias="ingressClassName")
    rules: list[NetworkingV1IngressRule] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="rules"
    )
    tls: list[NetworkingV1IngressTLS] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="tls"
    )


class NetworkingV1IngressStatus(KubeModel):
    load_balancer: NetworkingV1IngressLoadBalancerStatus = Field(
        default_factory=lambda: NetworkingV1IngressLoadBalancerStatus.model_construct(),
        alias="loadBalancer",
    )


class NetworkingV1IngressTLS(KubeModel):
    hosts: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="hosts"
    )
    secret_name: str | None = Field(default=None, alias="secretName")


class NetworkingV1NetworkPolicy(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["NetworkPolicy"] = Field(default="NetworkPolicy", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1NetworkPolicySpec = Field(
        default_factory=lambda: NetworkingV1NetworkPolicySpec.model_construct(), alias="spec"
    )


class NetworkingV1NetworkPolicyEgressRule(KubeModel):
    ports: list[NetworkingV1NetworkPolicyPort] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="ports"
    )
    to: list[NetworkingV1NetworkPolicyPeer] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="to"
    )


class NetworkingV1NetworkPolicyIngressRule(KubeModel):
    from_: list[NetworkingV1NetworkPolicyPeer] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="from"
    )
    ports: list[NetworkingV1NetworkPolicyPort] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="ports"
    )


class NetworkingV1NetworkPolicyList(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    items: list[NetworkingV1NetworkPolicy] = Field(alias="items")
    kind: Literal["NetworkPolicyList"] = Field(default="NetworkPolicyList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1NetworkPolicyPeer(KubeModel):
    ip_block: NetworkingV1IPBlock | None = Field(default=None, alias="ipBlock")
    namespace_selector: MetaV1LabelSelector | None = Field(default=None, alias="namespaceSelector")
    pod_selector: MetaV1LabelSelector | None = Field(default=None, alias="podSelector")


class NetworkingV1NetworkPolicyPort(KubeModel):
    end_port: int | None = Field(default=None, alias="endPort")
    port: IntOrString | None = Field(default=None, alias="port")
    protocol: str | None = Field(default=None, alias="protocol")


class NetworkingV1NetworkPolicySpec(KubeModel):
    egress: list[NetworkingV1NetworkPolicyEgressRule] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="egress"
    )
    ingress: list[NetworkingV1NetworkPolicyIngressRule] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="ingress"
    )
    pod_selector: MetaV1LabelSelector = Field(
        default_factory=lambda: MetaV1LabelSelector.model_construct(), alias="podSelector"
    )
    policy_types: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="policyTypes"
    )


class NetworkingV1ServiceBackendPort(KubeModel):
    name: str | None = Field(default=None, alias="name")
    number: int | None = Field(default=None, alias="number")


class NetworkingV1IPAddress(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["IPAddress"] = Field(default="IPAddress", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1IPAddressSpec = Field(
        default_factory=lambda: NetworkingV1IPAddressSpec.model_construct(), alias="spec"
    )


class NetworkingV1IPAddressList(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    items: list[NetworkingV1IPAddress] = Field(alias="items")
    kind: Literal["IPAddressList"] = Field(default="IPAddressList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1IPAddressSpec(KubeModel):
    parent_ref: NetworkingV1ParentReference = Field(alias="parentRef")


class NetworkingV1ParentReference(KubeModel):
    group: str | None = Field(default=None, alias="group")
    name: str = Field(alias="name")
    namespace: str | None = Field(default=None, alias="namespace")
    resource: str = Field(alias="resource")


class NetworkingV1ServiceCIDR(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    kind: Literal["ServiceCIDR"] = Field(default="ServiceCIDR", alias="kind")
    metadata: MetaV1ObjectMeta = Field(
        default_factory=lambda: MetaV1ObjectMeta.model_construct(), alias="metadata"
    )
    spec: NetworkingV1ServiceCIDRSpec = Field(
        default_factory=lambda: NetworkingV1ServiceCIDRSpec.model_construct(), alias="spec"
    )
    status: NetworkingV1ServiceCIDRStatus = Field(
        default_factory=lambda: NetworkingV1ServiceCIDRStatus.model_construct(), alias="status"
    )


class NetworkingV1ServiceCIDRList(KubeModel):
    api_version: Literal["networking.k8s.io/v1"] = Field(
        default="networking.k8s.io/v1", alias="apiVersion"
    )
    items: list[NetworkingV1ServiceCIDR] = Field(alias="items")
    kind: Literal["ServiceCIDRList"] = Field(default="ServiceCIDRList", alias="kind")
    metadata: MetaV1ListMeta = Field(
        default_factory=lambda: MetaV1ListMeta.model_construct(), alias="metadata"
    )


class NetworkingV1ServiceCIDRSpec(KubeModel):
    cidrs: list[str] | None = Field(
        default=None, json_schema_extra={"x-kubernetes-list-type": "atomic"}, alias="cidrs"
    )


class NetworkingV1ServiceCIDRStatus(KubeModel):
    conditions: list[MetaV1Condition] | None = Field(
        default=None,
        json_schema_extra={
            "x-kubernetes-list-map-keys": ["type"],
            "x-kubernetes-list-type": "map",
            "x-kubernetes-patch-merge-key": "type",
            "x-kubernetes-patch-strategy": "merge",
        },
        alias="conditions",
    )


__all__ = [
    "NetworkingV1HTTPIngressPath",
    "NetworkingV1HTTPIngressRuleValue",
    "NetworkingV1IPBlock",
    "NetworkingV1Ingress",
    "NetworkingV1IngressBackend",
    "NetworkingV1IngressClass",
    "NetworkingV1IngressClassList",
    "NetworkingV1IngressClassParametersReference",
    "NetworkingV1IngressClassSpec",
    "NetworkingV1IngressList",
    "NetworkingV1IngressLoadBalancerIngress",
    "NetworkingV1IngressLoadBalancerStatus",
    "NetworkingV1IngressPortStatus",
    "NetworkingV1IngressRule",
    "NetworkingV1IngressServiceBackend",
    "NetworkingV1IngressSpec",
    "NetworkingV1IngressStatus",
    "NetworkingV1IngressTLS",
    "NetworkingV1NetworkPolicy",
    "NetworkingV1NetworkPolicyEgressRule",
    "NetworkingV1NetworkPolicyIngressRule",
    "NetworkingV1NetworkPolicyList",
    "NetworkingV1NetworkPolicyPeer",
    "NetworkingV1NetworkPolicyPort",
    "NetworkingV1NetworkPolicySpec",
    "NetworkingV1ServiceBackendPort",
    "NetworkingV1IPAddress",
    "NetworkingV1IPAddressList",
    "NetworkingV1IPAddressSpec",
    "NetworkingV1ParentReference",
    "NetworkingV1ServiceCIDR",
    "NetworkingV1ServiceCIDRList",
    "NetworkingV1ServiceCIDRSpec",
    "NetworkingV1ServiceCIDRStatus",
]
