# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "FlowControlV1API": "httpx2_k8s.flowcontrol.v1._sync",
    "AsyncFlowControlV1API": "httpx2_k8s.flowcontrol.v1._async",
    "FlowControlV1ExemptPriorityLevelConfiguration": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowDistinguisherMethod": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowSchema": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowSchemaCondition": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowSchemaList": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowSchemaSpec": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1FlowSchemaStatus": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1GroupSubject": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1LimitResponse": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1LimitedPriorityLevelConfiguration": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1NonResourcePolicyRule": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PolicyRulesWithSubjects": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfiguration": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfigurationCondition": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfigurationList": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfigurationReference": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfigurationSpec": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1PriorityLevelConfigurationStatus": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1QueuingConfiguration": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1ResourcePolicyRule": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1ServiceAccountSubject": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1Subject": "httpx2_k8s.flowcontrol.v1._models",
    "FlowControlV1UserSubject": "httpx2_k8s.flowcontrol.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncFlowControlV1API",
    "FlowControlV1API",
    "FlowControlV1ExemptPriorityLevelConfiguration",
    "FlowControlV1FlowDistinguisherMethod",
    "FlowControlV1FlowSchema",
    "FlowControlV1FlowSchemaCondition",
    "FlowControlV1FlowSchemaList",
    "FlowControlV1FlowSchemaSpec",
    "FlowControlV1FlowSchemaStatus",
    "FlowControlV1GroupSubject",
    "FlowControlV1LimitResponse",
    "FlowControlV1LimitedPriorityLevelConfiguration",
    "FlowControlV1NonResourcePolicyRule",
    "FlowControlV1PolicyRulesWithSubjects",
    "FlowControlV1PriorityLevelConfiguration",
    "FlowControlV1PriorityLevelConfigurationCondition",
    "FlowControlV1PriorityLevelConfigurationList",
    "FlowControlV1PriorityLevelConfigurationReference",
    "FlowControlV1PriorityLevelConfigurationSpec",
    "FlowControlV1PriorityLevelConfigurationStatus",
    "FlowControlV1QueuingConfiguration",
    "FlowControlV1ResourcePolicyRule",
    "FlowControlV1ServiceAccountSubject",
    "FlowControlV1Subject",
    "FlowControlV1UserSubject",
]
