# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.autoscaling.v1._async import AsyncAutoscalingV1API as _ExistingAsyncAPI
from httpx2_k8s.autoscaling.v1._official_async import _OfficialAutoscalingV1AsyncOperations
from httpx2_k8s.autoscaling.v1._official_sync import _OfficialAutoscalingV1SyncOperations
from httpx2_k8s.autoscaling.v1._sync import AutoscalingV1API as _ExistingSyncAPI


class AutoscalingV1API(_ExistingSyncAPI, _OfficialAutoscalingV1SyncOperations):
    pass


class AsyncAutoscalingV1API(_ExistingAsyncAPI, _OfficialAutoscalingV1AsyncOperations):
    pass


__all__ = ["AsyncAutoscalingV1API", "AutoscalingV1API"]
