# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Iterator

import httpx2

from httpx2_k8s._api import resource_name
from httpx2_k8s._official_api import PatchContentType, iter_watch_response, query_parameters
from httpx2_k8s._protocols import SyncKubeClientProtocol
from httpx2_k8s.models import (
    AutoscalingV1HorizontalPodAutoscaler,
    AutoscalingV1HorizontalPodAutoscalerList,
    MetaV1APIResourceList,
    MetaV1DeleteOptions,
    MetaV1Patch,
    MetaV1Status,
    MetaV1WatchEvent,
)


class _OfficialAutoscalingV1SyncOperations:
    _client: SyncKubeClientProtocol

    def official_delete_collection_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        continue_token: str | None = None,
        dry_run: str | None = None,
        field_selector: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
    ) -> MetaV1Status:
        _path = (
            f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "continue": continue_token,
                "dryRun": dry_run,
                "fieldSelector": field_selector,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "labelSelector": label_selector,
                "limit": limit,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def official_delete_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        name: str,
        *,
        body: MetaV1DeleteOptions | None = None,
        pretty: str | None = None,
        dry_run: str | None = None,
        grace_period_seconds: int | None = None,
        ignore_store_read_error_with_cluster_breaking_potential: bool | None = None,
        orphan_dependents: bool | None = None,
        propagation_policy: str | None = None,
    ) -> MetaV1Status:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "gracePeriodSeconds": grace_period_seconds,
                "ignoreStoreReadErrorWithClusterBreakingPotential": ignore_store_read_error_with_cluster_breaking_potential,
                "orphanDependents": orphan_dependents,
                "propagationPolicy": propagation_policy,
            }
        )
        return self._client.request(
            "DELETE",
            _path,
            response_model=MetaV1Status,
            params=params,
            body=body,
        )

    def get_api_resources(
        self,
    ) -> MetaV1APIResourceList:
        _path = "/apis/autoscaling/v1/"
        params = {}
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1APIResourceList,
            params=params,
        )

    def official_list_horizontal_pod_autoscaler_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscalerList:
        _path = "/apis/autoscaling/v1/horizontalpodautoscalers"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscalerList,
            params=params,
        )

    def official_list_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        *,
        pretty: str | None = None,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscalerList:
        _path = (
            f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscalerList,
            params=params,
        )

    def official_read_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
        )

    def official_read_namespaced_horizontal_pod_autoscaler_status(
        self,
        namespace: str,
        name: str,
        *,
        pretty: str | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
        )

    def watch_horizontal_pod_autoscaler_list_for_all_namespaces(
        self,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = "/apis/autoscaling/v1/watch/horizontalpodautoscalers"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_namespaced_horizontal_pod_autoscaler_list(
        self,
        namespace: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> MetaV1WatchEvent:
        _path = f"/apis/autoscaling/v1/watch/namespaces/{resource_name(namespace)}/horizontalpodautoscalers"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return self._client.request(
            "GET",
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def watch_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        name: str,
        *,
        allow_watch_bookmarks: bool | None = None,
        continue_token: str | None = None,
        field_selector: str | None = None,
        label_selector: str | None = None,
        limit: int | None = None,
        pretty: str | None = None,
        resource_version: str | None = None,
        resource_version_match: str | None = None,
        send_initial_events: bool | None = None,
        shard_selector: str | None = None,
        timeout_seconds: int | None = None,
        watch: bool | None = None,
    ) -> Iterator[MetaV1WatchEvent]:
        _path = f"/apis/autoscaling/v1/watch/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}"
        params = query_parameters(
            {
                "allowWatchBookmarks": allow_watch_bookmarks,
                "continue": continue_token,
                "fieldSelector": field_selector,
                "labelSelector": label_selector,
                "limit": limit,
                "pretty": pretty,
                "resourceVersion": resource_version,
                "resourceVersionMatch": resource_version_match,
                "sendInitialEvents": send_initial_events,
                "shardSelector": shard_selector,
                "timeoutSeconds": timeout_seconds,
                "watch": watch,
            }
        )
        return iter_watch_response(
            self._client,
            _path,
            response_model=MetaV1WatchEvent,
            params=params,
        )

    def official_patch_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_patch_namespaced_horizontal_pod_autoscaler_status(
        self,
        namespace: str,
        name: str,
        body: MetaV1Patch,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
        force: bool | None = None,
        content_type: PatchContentType = "application/strategic-merge-patch+json",
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
                "force": force,
            }
        )
        return self._client.request(
            "PATCH",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
            body=body,
            content_type=content_type,
        )

    def official_create_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        body: AutoscalingV1HorizontalPodAutoscaler,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = (
            f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers"
        )
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "POST",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
            body=body,
        )

    def official_replace_namespaced_horizontal_pod_autoscaler(
        self,
        namespace: str,
        name: str,
        body: AutoscalingV1HorizontalPodAutoscaler,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
            body=body,
        )

    def official_replace_namespaced_horizontal_pod_autoscaler_status(
        self,
        namespace: str,
        name: str,
        body: AutoscalingV1HorizontalPodAutoscaler,
        *,
        pretty: str | None = None,
        dry_run: str | None = None,
        field_manager: str | None = None,
        field_validation: str | None = None,
    ) -> AutoscalingV1HorizontalPodAutoscaler:
        _path = f"/apis/autoscaling/v1/namespaces/{resource_name(namespace)}/horizontalpodautoscalers/{resource_name(name)}/status"
        params = query_parameters(
            {
                "pretty": pretty,
                "dryRun": dry_run,
                "fieldManager": field_manager,
                "fieldValidation": field_validation,
            }
        )
        return self._client.request(
            "PUT",
            _path,
            response_model=AutoscalingV1HorizontalPodAutoscaler,
            params=params,
            body=body,
        )
