# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.resource.v1beta2._async import AsyncResourceV1Beta2API
from httpx2_k8s.resource.v1beta2._sync import ResourceV1Beta2API

__all__ = ["AsyncResourceV1Beta2API", "ResourceV1Beta2API"]
