# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "BatchV1API": "httpx2_k8s.batch.v1._facade",
    "AsyncBatchV1API": "httpx2_k8s.batch.v1._facade",
    "BatchV1CronJob": "httpx2_k8s.batch.v1._models",
    "BatchV1CronJobList": "httpx2_k8s.batch.v1._models",
    "BatchV1CronJobSpec": "httpx2_k8s.batch.v1._models",
    "BatchV1CronJobStatus": "httpx2_k8s.batch.v1._models",
    "BatchV1Job": "httpx2_k8s.batch.v1._models",
    "BatchV1JobCondition": "httpx2_k8s.batch.v1._models",
    "BatchV1JobList": "httpx2_k8s.batch.v1._models",
    "BatchV1JobSpec": "httpx2_k8s.batch.v1._models",
    "BatchV1JobStatus": "httpx2_k8s.batch.v1._models",
    "BatchV1JobTemplateSpec": "httpx2_k8s.batch.v1._models",
    "BatchV1PodFailurePolicy": "httpx2_k8s.batch.v1._models",
    "BatchV1PodFailurePolicyOnExitCodesRequirement": "httpx2_k8s.batch.v1._models",
    "BatchV1PodFailurePolicyOnPodConditionsPattern": "httpx2_k8s.batch.v1._models",
    "BatchV1PodFailurePolicyRule": "httpx2_k8s.batch.v1._models",
    "BatchV1SuccessPolicy": "httpx2_k8s.batch.v1._models",
    "BatchV1SuccessPolicyRule": "httpx2_k8s.batch.v1._models",
    "BatchV1UncountedTerminatedPods": "httpx2_k8s.batch.v1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncBatchV1API",
    "BatchV1API",
    "BatchV1CronJob",
    "BatchV1CronJobList",
    "BatchV1CronJobSpec",
    "BatchV1CronJobStatus",
    "BatchV1Job",
    "BatchV1JobCondition",
    "BatchV1JobList",
    "BatchV1JobSpec",
    "BatchV1JobStatus",
    "BatchV1JobTemplateSpec",
    "BatchV1PodFailurePolicy",
    "BatchV1PodFailurePolicyOnExitCodesRequirement",
    "BatchV1PodFailurePolicyOnPodConditionsPattern",
    "BatchV1PodFailurePolicyRule",
    "BatchV1SuccessPolicy",
    "BatchV1SuccessPolicyRule",
    "BatchV1UncountedTerminatedPods",
]
