# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from httpx2_k8s.autoscaling.v2._async import AsyncAutoscalingV2API as _ExistingAsyncAPI
from httpx2_k8s.autoscaling.v2._official_async import _OfficialAutoscalingV2AsyncOperations
from httpx2_k8s.autoscaling.v2._official_sync import _OfficialAutoscalingV2SyncOperations
from httpx2_k8s.autoscaling.v2._sync import AutoscalingV2API as _ExistingSyncAPI


class AutoscalingV2API(_ExistingSyncAPI, _OfficialAutoscalingV2SyncOperations):
    pass


class AsyncAutoscalingV2API(_ExistingAsyncAPI, _OfficialAutoscalingV2AsyncOperations):
    pass
