# Generated by scripts/generate_official_apis.py; do not edit by hand.
# ruff: noqa
from __future__ import annotations

from httpx2_k8s._lazy import load_export

_LAZY_IMPORTS = {
    "CertificatesV1Alpha1API": "httpx2_k8s.certificates.v1alpha1._sync",
    "AsyncCertificatesV1Alpha1API": "httpx2_k8s.certificates.v1alpha1._async",
    "CertificatesV1Alpha1ClusterTrustBundle": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1ClusterTrustBundleList": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1ClusterTrustBundleSpec": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1PodCertificateRequest": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1PodCertificateRequestList": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1PodCertificateRequestSpec": "httpx2_k8s.certificates.v1alpha1._models",
    "CertificatesV1Alpha1PodCertificateRequestStatus": "httpx2_k8s.certificates.v1alpha1._models",
}


def __getattr__(name: str) -> object:
    return load_export(name, __name__, globals(), _LAZY_IMPORTS)


__all__ = [
    "AsyncCertificatesV1Alpha1API",
    "CertificatesV1Alpha1API",
    "CertificatesV1Alpha1ClusterTrustBundle",
    "CertificatesV1Alpha1ClusterTrustBundleList",
    "CertificatesV1Alpha1ClusterTrustBundleSpec",
    "CertificatesV1Alpha1PodCertificateRequest",
    "CertificatesV1Alpha1PodCertificateRequestList",
    "CertificatesV1Alpha1PodCertificateRequestSpec",
    "CertificatesV1Alpha1PodCertificateRequestStatus",
]
