# Generated by scripts/generate_official_apis.py; do not edit by hand.
from httpx2_k8s.certificates.v1alpha1._official_async import (
    _OfficialCertificatesV1Alpha1AsyncOperations,
)


class AsyncCertificatesV1Alpha1API(_OfficialCertificatesV1Alpha1AsyncOperations):
    pass
